#version 330 core
// LunarGOO output
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
layout(std140, binding = 2 ) uniform PerViewConstantBuffer_t {
	layout(row_major) mat4 g_matWorldToProjection;
	layout(row_major) mat4 g_matProjectionToWorld;
	layout(row_major) mat4 g_matWorldToView;
	layout(row_major) mat4 g_matViewToProjection;
	vec4 g_vInvProjRow3;
	vec4 g_vClipPlane0;
	float g_flToneMapScalarLinear;
	float g_flLightMapScalar;
	float g_flEnvMapScalar;
	float g_flToneMapScalarGamma;
	vec3 g_vCameraPositionWs;
	float g_flViewportMinZ;
	vec3 g_vCameraDirWs;
	float g_flViewportMaxZ;
	vec3 g_vCameraUpDirWs;
	float g_flTime;
	vec3 g_vDepthPsToVsConversion;
	float g_flNearPlane;
	float g_flFarPlane;
	float g_flLightBinnerFarPlane;
	vec2 g_vInvViewportSize;
	vec2 g_vViewportToGBufferRatio;
	vec2 g_vMorphTextureAtlasSize;
	vec4 g_vInvGBufferSize;
	vec2 g_vViewportOffset;
	vec2 g_vViewportSize;
	vec2 g_vRenderTargetSize;
	float g_flFogBlendToBackground;
	float g_flHenyeyGreensteinCoeff;
	vec3 g_vFogColor;
	float g_flNegFogStartOverFogRange;
	float g_flInvFogRange;
	float g_flFogMaxDensity;
	float g_flFogExponent;
	float g_flMod2xIdentity;
	vec2 g_bRoughnessParams;
	float g_bStereoEnabled;
	float g_flStereoCameraIndex;
	vec3 g_vMiddleEyePositionWs;
	float g_flPad2;
	layout(row_major) mat4 g_matWorldToProjectionMultiview[2];
	vec4 g_vCameraPositionWsMultiview[2];
	vec4 g_vFrameBufferCopyInvSizeAndUvScale;
	vec4 g_vCameraAngles;
	vec4 g_vWorldToCameraOffset;
	vec4 g_vWorldToCameraOffsetMultiview[2];
	vec4 g_vPerViewConstantExtraData0;
	vec4 g_vPerViewConstantExtraData1;
	vec4 g_vPerViewConstantExtraData2;
	vec4 g_vPerViewConstantExtraData3;
} ;
layout(std140, binding = 1 ) uniform DotaGlobalParams_t {
	vec3 g_vGlobalLightDir;
	vec3 g_vGlobalLightColor;
	float g_flGlobalLightSpecularScale;
	vec3 g_vGlobalLightSpecularDir;
	float g_flGlobalLightSpecularExp;
	vec3 g_vGlobalLightSpecularColor;
	float g_flGlobalLightSpecularIndependence;
	vec3 g_vGlobalLightAmbientDir;
	float g_flGlobalLightAmbientScale1;
	vec3 g_vGlobalLightAmbientColor1;
	float g_flGlobalLightAmbientScale2;
	vec3 g_vGlobalLightAmbientColor2;
	float g_flGlobalLightAmbientScale2Hero;
	vec2 g_vGlobalCloud1Offset;
	vec2 g_vGlobalCloud2Offset;
	vec3 g_vFowColor;
	float g_flGlobalCloudScale;
	float g_flFowDarkness;
	float g_flFowGrayFactor;
	float g_flFowColorFactor;
	float g_flFowGrayHilights;
	vec4 g_vFowWorldSize;
	vec4 g_vFowTexOffsets;
	layout(row_major) mat4 g_matShadowWorldToTexture;
	vec4 g_vInvShadowDepthTextureSize;
	vec3 g_vGlobalLightAmbientColor3;
	float g_flGlobalLightAmbientShadowAmount;
} ;
layout( binding = 1 ) uniform sampler2DShadow g_tShadowDepthTexture;
layout( binding = 0 ) uniform sampler2D g_tColor;
layout(std140, binding = 0 ) uniform _Globals_ {
	float g_flBumpStrength;
	vec3 g_vColorTint;
	vec3 g_vColorTint2;
	float g_flOpacityScale;
	float g_flCubeMapScalarExterior;
	float g_flCubeMapScalarInterior;
	vec2 g_vTexCoordScale;
	float g_flSpecularIntensity;
	float g_flFresnelReflectance;
	float g_flFresnelExponent;
	float g_flBloom;
} ;
layout( binding = 2 ) uniform samplerCube g_tCubeMapInterior;
layout( binding = 3 ) uniform sampler2D g_tFow;
uniform sampler2D g_tFrameBufferCopyTexture;
uniform sampler2D g_tDepthTexture;
uniform sampler2D g_tGBufferAlbedo;
uniform sampler2D g_tGBufferLightingTerms;
uniform sampler2D g_tGBufferDepth;
uniform sampler2D g_tGBufferNormalWs;
layout(std140) uniform PerViewLightingConstantBuffer_t {
	vec4 g_vInvLightTextureDims;
	vec4 g_vLightBinCounts;
	vec2 g_vLowResDeferredLightingTextureDim;
	vec2 g_vLowResDeferredLightingTextureInvDim;
	vec3 g_vToolsAmbientLighting;
	float g_flSSAOEnabled;
	vec3 g_vIrradAtlasInvSize;
	float g_flIrradGlobalLightingFactor;
	vec4 g_vGlobalLightingSHRed;
	vec4 g_vGlobalLightingSHGreen;
	vec4 g_vGlobalLightingSHBlue;
	vec3 g_vRayleighScatteringCoeff;
	float g_flMieScatteringEccentricity;
	vec3 g_vMieScatteringCoeff;
	float g_flMieForwardScatteringRatio;
	vec3 g_vSpecularCubeMapScale;
	float g_flDefaultEnvMapIndex;
	vec4 g_vLightCookieSheetSequenceAndSizes;
	vec3 g_vLpvBoxMinCascade0;
	float g_flLpvBrightnessScale;
	vec3 g_vLpvInvBoxDimCascade0;
	vec2 g_vLpvInvCoeffTextureDim;
} ;
layout(std140) uniform PerLayerConstantBuffer_t {
	vec4 g_vWireframeColor;
} ;
uniform sampler2D g_tClouds;
uniform samplerCube g_tCubeMapExterior;
layout(location=0) in vec2 PS_INPUT_gl_vBaseTexCoord;
layout(location=1) in vec4 PS_INPUT_gl_vPositionWs_flLinearDepth;
layout(location=2) in vec3 PS_INPUT_gl_vNormalWs;
layout(location=3) in vec4 PS_INPUT_gl_vVertexColor;
layout(location=0) out vec4 PS_OUTPUT_gl_vDiffuse;
layout(location=1) out vec4 PS_OUTPUT_gl_vSpecular;
layout(location=2) out vec4 PS_OUTPUT_gl_vDepth;
layout(location=3) out vec4 PS_OUTPUT_gl_vNormalWs;
const vec3 C_vec3pa1d0p = vec3(-1.0);
const vec3 C_vec3p0d0p = vec3(0.0);
const float C_0d0 = 0.0;
const float C_1d0 = 1.0;
const vec4 C_wt9i7t = vec4(0.0749064);
const vec2 C_a1z03r = vec2(0.0, 0.0);
const vec4 C_a1xzaw1 = vec4(0.123596);
const float C_0d205993 = 0.205993;
const float C_1d85 = 1.85;
const float C_0d45 = 0.45;
const float C_2d1 = 2.1;
const float C_0d5 = 0.5;
const vec3 C_kfumqy1 = vec3(0.2125, 0.7154, 0.0721);
const vec3 C_vec3p0d5p = vec3(0.5);
const vec4 C_d5y0kt1 = vec4(0.0, 1.0, 0.0, 0.0);
void main()
{
	vec3 H_8hpfi81 = PS_INPUT_gl_vNormalWs * C_vec3pa1d0p;
	vec3 vGeometricNormalWs = normalize(H_8hpfi81);
	vec4 vAlbedo = texture(g_tColor, PS_INPUT_gl_vBaseTexCoord);
	vec3 H_jqml65 = g_vColorTint * vAlbedo.xyz;
	vec3 H_36u4ia = H_jqml65 * g_vColorTint;
	vec3 H_bsagln1 = H_36u4ia * PS_INPUT_gl_vVertexColor.xyz;
	vec3 H_j03jbn = C_vec3p0d0p - g_vGlobalLightDir;
	float flNDotL = dot(H_j03jbn, vGeometricNormalWs);
	float misc3a = clamp(flNDotL, C_0d0, C_1d0);
	float product = PS_INPUT_gl_vPositionWs_flLinearDepth.x * g_matShadowWorldToTexture[0].x;
	float product1 = PS_INPUT_gl_vPositionWs_flLinearDepth.y * g_matShadowWorldToTexture[1].x;
	float dotProduct = product + product1;
	float product2 = PS_INPUT_gl_vPositionWs_flLinearDepth.z * g_matShadowWorldToTexture[2].x;
	float dotProduct1 = dotProduct + product2;
	float dotProduct2 = dotProduct1 + g_matShadowWorldToTexture[3].x;
	float product3 = PS_INPUT_gl_vPositionWs_flLinearDepth.x * g_matShadowWorldToTexture[0].y;
	float product4 = PS_INPUT_gl_vPositionWs_flLinearDepth.y * g_matShadowWorldToTexture[1].y;
	float dotProduct3 = product3 + product4;
	float product5 = PS_INPUT_gl_vPositionWs_flLinearDepth.z * g_matShadowWorldToTexture[2].y;
	float dotProduct4 = dotProduct3 + product5;
	float dotProduct5 = dotProduct4 + g_matShadowWorldToTexture[3].y;
	float product6 = PS_INPUT_gl_vPositionWs_flLinearDepth.x * g_matShadowWorldToTexture[0].z;
	float product7 = PS_INPUT_gl_vPositionWs_flLinearDepth.y * g_matShadowWorldToTexture[1].z;
	float dotProduct6 = product6 + product7;
	float product8 = PS_INPUT_gl_vPositionWs_flLinearDepth.z * g_matShadowWorldToTexture[2].z;
	float dotProduct7 = dotProduct6 + product8;
	float dotProduct8 = dotProduct7 + g_matShadowWorldToTexture[3].z;
	float product9 = PS_INPUT_gl_vPositionWs_flLinearDepth.x * g_matShadowWorldToTexture[0].w;
	float producta = PS_INPUT_gl_vPositionWs_flLinearDepth.y * g_matShadowWorldToTexture[1].w;
	float dotProduct9 = product9 + producta;
	float productb = PS_INPUT_gl_vPositionWs_flLinearDepth.z * g_matShadowWorldToTexture[2].w;
	float dotProducta = dotProduct9 + productb;
	float dotProductb = dotProducta + g_matShadowWorldToTexture[3].w;
	vec3 H_16wbh81 = vec3(dotProductb);
	vec3 H_mo5dbs1 = vec3(dotProduct2, dotProduct5, dotProduct8);
	vec3 H_qdsg5k1 = H_mo5dbs1 / H_16wbh81;
	float param = C_0d0 - H_qdsg5k1.z;
	float misc3a1 = clamp(param, C_0d0, C_1d0);
	float H_60ojyb = C_0d0 - g_vInvShadowDepthTextureSize.x;
	vec2 H_t5te6f = vec2(H_60ojyb);
	vec2 H_ep5c3j1 = H_qdsg5k1.xy + g_vInvShadowDepthTextureSize.xx;
	vec3 H_vuqeij1 = vec3(H_ep5c3j1.x, H_ep5c3j1.y, misc3a1);
	float H_28oipf1 = textureLod(g_tShadowDepthTexture, H_vuqeij1, C_0d0);
	vec2 H_pv0in9 = vec2(H_60ojyb, g_vInvShadowDepthTextureSize.x);
	vec2 H_he48ts = H_pv0in9 + H_qdsg5k1.xy;
	vec3 H_jppbus1 = vec3(H_he48ts.x, H_he48ts.y, misc3a1);
	float H_ivhdzs = textureLod(g_tShadowDepthTexture, H_jppbus1, C_0d0);
	vec2 H_t32u4i1 = vec2(g_vInvShadowDepthTextureSize.x, H_60ojyb);
	vec2 H_3zubtq = H_qdsg5k1.xy + H_t32u4i1;
	vec3 H_n148fq = vec3(H_3zubtq.x, H_3zubtq.y, misc3a1);
	float H_dpd2541 = textureLod(g_tShadowDepthTexture, H_n148fq, C_0d0);
	vec2 H_r37y1w = H_qdsg5k1.xy + H_t5te6f;
	vec3 H_za7hkm = vec3(H_r37y1w.x, H_r37y1w.y, misc3a1);
	float H_b6h98q = textureLod(g_tShadowDepthTexture, H_za7hkm, C_0d0);
	vec4 H_5m1jtj1 = vec4(H_28oipf1, H_ivhdzs, H_dpd2541, H_b6h98q);
	float flSum = dot(H_5m1jtj1, C_wt9i7t);
	vec2 H_e9rh661 = vec2(g_vInvShadowDepthTextureSize.x, C_0d0);
	vec2 H_85dk7x = H_e9rh661 + H_qdsg5k1.xy;
	vec3 H_nuhisf = vec3(H_85dk7x.x, H_85dk7x.y, misc3a1);
	float H_6d1hyw = textureLod(g_tShadowDepthTexture, H_nuhisf, C_0d0);
	vec2 H_na4vhz = vec2(H_60ojyb, C_0d0);
	vec2 H_iybrli = H_na4vhz + H_qdsg5k1.xy;
	vec3 H_r56xpt = vec3(H_iybrli.x, H_iybrli.y, misc3a1);
	float H_ij9vx3 = textureLod(g_tShadowDepthTexture, H_r56xpt, C_0d0);
	vec2 H_23b4ob1 = C_a1z03r;
	H_23b4ob1.y = H_60ojyb;
	vec2 H_wcm3cs = H_23b4ob1 + H_qdsg5k1.xy;
	vec3 H_bg2omn1 = vec3(H_wcm3cs.x, H_wcm3cs.y, misc3a1);
	float H_jc31jt = textureLod(g_tShadowDepthTexture, H_bg2omn1, C_0d0);
	vec2 H_23b4ob1r = C_a1z03r;
	H_23b4ob1r.y = g_vInvShadowDepthTextureSize.x;
	vec2 H_omz8p81 = H_23b4ob1r + H_qdsg5k1.xy;
	vec3 H_nh5i681 = vec3(H_omz8p81.x, H_omz8p81.y, misc3a1);
	float H_wy2hek = textureLod(g_tShadowDepthTexture, H_nh5i681, C_0d0);
	vec4 H_3uv3kl1 = vec4(H_6d1hyw, H_ij9vx3, H_jc31jt, H_wy2hek);
	float flSum1 = dot(H_3uv3kl1, C_a1xzaw1);
	float flSum2 = flSum + flSum1;
	vec3 H_ls2vnt1 = vec3(H_qdsg5k1.x, H_qdsg5k1.y, misc3a1);
	float flSum3 = textureLod(g_tShadowDepthTexture, H_ls2vnt1, C_0d0);
	float H_xchcee1 = flSum3 * C_0d205993;
	float flSum4 = H_xchcee1 + flSum2;
	float flDirectionalAmbientShadow = mix(C_1d0, flSum4, g_flGlobalLightAmbientShadowAmount);
	float flDirectOcclusionFactor = pow(C_1d0, C_1d85);
	float flDirectOcclusionFactor1 = mix(C_0d45, C_1d0, flDirectOcclusionFactor);
	float flIndirectOcclusionFactor = pow(C_1d0, C_2d1);
	vec3 H_fx1uua = vec3(g_flGlobalLightAmbientScale1);
	vec3 vDirectionalAmbientColor = H_fx1uua * g_vGlobalLightAmbientColor1;
	float H_guttgv1 = vGeometricNormalWs.z * C_0d5;
	float H_0yyagq1 = C_0d5 + H_guttgv1;
	vec3 vShadowAmbientColor = mix(g_vGlobalLightAmbientColor3, g_vGlobalLightAmbientColor2, H_0yyagq1);
	vec3 H_s7noda1 = vec3(g_flGlobalLightAmbientScale2);
	vec3 vShadowAmbientColor1 = H_s7noda1 * vShadowAmbientColor;
	float flLuminance = dot(vDirectionalAmbientColor, C_kfumqy1);
	vec3 H_t1lelu1 = vec3(flLuminance);
	float flLuminance1 = dot(vShadowAmbientColor1, C_kfumqy1);
	vec3 H_chpant1 = vec3(flLuminance1);
	vec3 vDirectionalAmbientColor1 = mix(vDirectionalAmbientColor, H_t1lelu1, C_vec3p0d0p);
	vec3 vShadowAmbientColor2 = mix(vShadowAmbientColor1, H_chpant1, C_vec3p0d0p);
	float H_gjd0nq1 = flSum4 * misc3a;
	float H_999p8j = H_gjd0nq1 * flDirectOcclusionFactor1;
	vec3 H_56168t1 = vec3(H_999p8j);
	vec3 vDirectLight = H_56168t1 * g_vGlobalLightColor;
	float vDirectionalAmbientLight = dot(g_vGlobalLightAmbientDir, vGeometricNormalWs);
	float misc3a2 = clamp(vDirectionalAmbientLight, C_0d0, C_1d0);
	float H_j74xze = flDirectionalAmbientShadow * misc3a2;
	float H_e8ryxj = H_j74xze * flIndirectOcclusionFactor;
	vec3 H_sv6s9y1 = vec3(H_e8ryxj);
	vec3 vDirectionalAmbientLight1 = H_sv6s9y1 * vDirectionalAmbientColor1;
	float H_lua7si = C_1d0 - H_gjd0nq1;
	float H_37qwjd = H_lua7si * flIndirectOcclusionFactor;
	vec3 H_q7vhfl = vec3(H_37qwjd);
	vec3 vShadowAmbientLight = H_q7vhfl * vShadowAmbientColor2;
	vec3 H_8w78gv1 = vDirectLight + vDirectionalAmbientLight1;
	vec3 vLighting = H_8w78gv1 + vShadowAmbientLight;
	vec3 vDiffuse = H_bsagln1 * vLighting;
	vec3 H_8mjky01 = PS_INPUT_gl_vPositionWs_flLinearDepth.xyz - g_vCameraPositionWs;
	vec3 H_i1nbjv1 = normalize(H_8mjky01);
	vec3 H_t3ywhi1 = C_vec3p0d0p - H_i1nbjv1;
	vec3 vReflect = reflect(H_t3ywhi1, vGeometricNormalWs);
	float flSpecular = dot(g_vGlobalLightSpecularDir, vReflect);
	float misc3a3 = clamp(flSpecular, C_0d0, C_1d0);
	float flSpecular1 = pow(misc3a3, g_flGlobalLightSpecularExp);
	float flSpecular2 = flSpecular1 * g_flSpecularIntensity;
	float flSpecular3 = PS_INPUT_gl_vVertexColor.w * flSpecular2;
	vec3 H_tp9b8o = vec3(flSpecular3);
	vec3 vSpecularRGB = H_tp9b8o * g_vGlobalLightSpecularColor;
	vec3 H_yisnc8 = C_vec3p0d0p - vReflect;
	vec4 vCubeMap = texture(g_tCubeMapInterior, H_yisnc8);
	vec3 H_6x2mwr1 = vec3(g_flCubeMapScalarInterior);
	vec3 vCubeMap1 = H_6x2mwr1 * vCubeMap.xyz;
	vec3 H_e3gb6g = PS_INPUT_gl_vVertexColor.www * vCubeMap1;
	vec3 vSpecularRGB1 = H_e3gb6g + vSpecularRGB;
	float flVDotNk = dot(H_t3ywhi1, vGeometricNormalWs);
	float misc3a4 = clamp(flVDotNk, C_0d0, C_1d0);
	float H_9bwy73 = C_1d0 - misc3a4;
	float flVDotNk1 = abs(H_9bwy73);
	float flVDotNk2 = pow(flVDotNk1, g_flFresnelExponent);
	float H_0fby2a1 = C_1d0 - g_flFresnelReflectance;
	float H_lplz5w1 = H_0fby2a1 * flVDotNk2;
	float H_vlq1ik1 = H_lplz5w1 + g_flFresnelReflectance;
	vec3 H_dyq7zc1 = vec3(H_vlq1ik1);
	vec3 vSpecularRGB2 = H_dyq7zc1 * vSpecularRGB1;
	vec3 vDiffuse1 = vDiffuse + vSpecularRGB2;
	vec2 H_n3d8b6 = PS_INPUT_gl_vPositionWs_flLinearDepth.xy * g_vFowWorldSize.zw;
	vec2 H_wmk3nj = H_n3d8b6 + g_vFowWorldSize.xy;
	vec4 flFowResult = texture(g_tFow, H_wmk3nj);
	vec4 H_rzb0vt = vec4(vDiffuse1.x, vDiffuse1.y, vDiffuse1.z, C_1d0);
	vec3 H_fcuksf = vGeometricNormalWs * C_vec3p0d5p;
	vec3 H_j223wv1 = C_vec3p0d5p + H_fcuksf;
	vec4 H_18jcae = vec4(H_j223wv1.x, H_j223wv1.y, H_j223wv1.z, C_0d0);
	float flLuminance2 = dot(vSpecularRGB2, C_kfumqy1);
	float H_i2aa5s = flLuminance2 * g_flBloom;
	float H_y0oq9l = H_i2aa5s * flFowResult.x;
	vec4 H_h8msa21 = C_d5y0kt1;
	H_h8msa21.zw = vec2(H_y0oq9l, C_0d0);
	PS_OUTPUT_gl_vDiffuse = H_rzb0vt;
	PS_OUTPUT_gl_vSpecular = H_h8msa21;
	PS_OUTPUT_gl_vDepth = PS_INPUT_gl_vPositionWs_flLinearDepth.wwww;
	PS_OUTPUT_gl_vNormalWs = H_18jcae;
}
