#version 330 core
// LunarGOO output
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
layout(std140) uniform PerViewConstantBuffer_t {
	layout(row_major) mat4 g_matWorldToProjection;
	layout(row_major) mat4 g_matProjectionToWorld;
	layout(row_major) mat4 g_matWorldToView;
	layout(row_major) mat4 g_matViewToProjection;
	vec4 g_vInvProjRow3;
	vec4 g_vClipPlane0;
	float g_flToneMapScalarLinear;
	float g_flLightMapScalar;
	float g_flEnvMapScalar;
	float g_flToneMapScalarGamma;
	vec3 g_vCameraPositionWs;
	float g_flViewportMinZ;
	vec3 g_vCameraDirWs;
	float g_flViewportMaxZ;
	vec3 g_vCameraUpDirWs;
	float g_flTime;
	vec3 g_vDepthPsToVsConversion;
	float g_flNearPlane;
	float g_flFarPlane;
	float g_flLightBinnerFarPlane;
	vec2 g_vInvViewportSize;
	vec2 g_vViewportToGBufferRatio;
	vec2 g_vMorphTextureAtlasSize;
	vec4 g_vInvGBufferSize;
	vec2 g_vViewportOffset;
	vec2 g_vViewportSize;
	vec2 g_vRenderTargetSize;
	float g_flFogBlendToBackground;
	float g_flHenyeyGreensteinCoeff;
	vec3 g_vFogColor;
	float g_flNegFogStartOverFogRange;
	float g_flInvFogRange;
	float g_flFogMaxDensity;
	float g_flFogExponent;
	float g_flMod2xIdentity;
	vec2 g_bRoughnessParams;
	float g_bStereoEnabled;
	float g_flStereoCameraIndex;
	vec3 g_vMiddleEyePositionWs;
	float g_flPad2;
	layout(row_major) mat4 g_matWorldToProjectionMultiview[2];
	vec4 g_vCameraPositionWsMultiview[2];
	vec4 g_vFrameBufferCopyInvSizeAndUvScale;
	vec4 g_vCameraAngles;
	vec4 g_vWorldToCameraOffset;
	vec4 g_vWorldToCameraOffsetMultiview[2];
	vec4 g_vPerViewConstantExtraData0;
	vec4 g_vPerViewConstantExtraData1;
	vec4 g_vPerViewConstantExtraData2;
	vec4 g_vPerViewConstantExtraData3;
} ;
layout(std140, binding = 0 ) uniform _Globals_ {
	vec4 g_vInvTextureDim;
	float g_flOverbrightAmount;
} ;
layout( binding = 0 ) uniform sampler2D g_tInputTexture;
layout(std140) uniform PerViewLightingConstantBuffer_t {
	vec4 g_vInvLightTextureDims;
	vec4 g_vLightBinCounts;
	vec2 g_vLowResDeferredLightingTextureDim;
	vec2 g_vLowResDeferredLightingTextureInvDim;
	vec3 g_vToolsAmbientLighting;
	float g_flSSAOEnabled;
	vec3 g_vIrradAtlasInvSize;
	float g_flIrradGlobalLightingFactor;
	vec4 g_vGlobalLightingSHRed;
	vec4 g_vGlobalLightingSHGreen;
	vec4 g_vGlobalLightingSHBlue;
	vec3 g_vRayleighScatteringCoeff;
	float g_flMieScatteringEccentricity;
	vec3 g_vMieScatteringCoeff;
	float g_flMieForwardScatteringRatio;
	vec3 g_vSpecularCubeMapScale;
	float g_flDefaultEnvMapIndex;
	vec4 g_vLightCookieSheetSequenceAndSizes;
	vec3 g_vLpvBoxMinCascade0;
	float g_flLpvBrightnessScale;
	vec3 g_vLpvInvBoxDimCascade0;
	vec2 g_vLpvInvCoeffTextureDim;
} ;
layout(std140) uniform PerLayerConstantBuffer_t {
	vec4 g_vWireframeColor;
} ;
layout(location=0) in vec2 PS_INPUT_gl_vTexCoord;
layout(location=0) out vec4 PS_OUTPUT_gl_vColor;
const float C_0d004433 = 0.004433;
const float C_0d296042 = 0.296042;
const float C_0d39905 = 0.39905;
const float C_0d0 = 0.0;
const float C_a3d0 = -3.0;
const float C_a1d18243 = -1.18243;
const float C_1d18243 = 1.18243;
const float C_3d0 = 3.0;
const float C_0d8 = 0.8;
void main()
{
	vec4 H_ka9o0y1 = vec4(C_0d004433);
	vec4 H_taux441 = vec4(C_0d296042);
	vec4 H_snzlur = vec4(C_0d39905);
	vec2 H_aogyom = vec2(C_0d0);
	vec4 H_taux441r = vec4(C_0d296042);
	vec4 H_ka9o0y1r = vec4(C_0d004433);
	float H_thgq4g = g_vInvTextureDim.x * C_a3d0;
	vec2 H_6ao3ts = vec2(H_thgq4g, C_0d0);
	vec2 vUvTmp = H_6ao3ts + PS_INPUT_gl_vTexCoord;
	vec4 vSample = texture(g_tInputTexture, vUvTmp);
	vec4 H_yto2x = H_ka9o0y1r * vSample;
	float H_rhp7a61 = g_vInvTextureDim.x * C_a1d18243;
	vec2 H_8ajf141 = vec2(H_rhp7a61, C_0d0);
	vec2 vUvTmp1 = H_8ajf141 + PS_INPUT_gl_vTexCoord;
	vec4 vSample1 = texture(g_tInputTexture, vUvTmp1);
	vec4 H_mnjn8h1 = H_taux441r * vSample1;
	vec4 H_4s1fbe = H_mnjn8h1 + H_yto2x;
	vec2 vUvTmp2 = H_aogyom + PS_INPUT_gl_vTexCoord;
	vec4 vSample2 = texture(g_tInputTexture, vUvTmp2);
	vec4 H_swa0zz = H_snzlur * vSample2;
	vec4 H_oasu0m1 = H_4s1fbe + H_swa0zz;
	float H_05bpqj = g_vInvTextureDim.x * C_1d18243;
	vec2 H_dozr661 = vec2(H_05bpqj, C_0d0);
	vec2 vUvTmp3 = H_dozr661 + PS_INPUT_gl_vTexCoord;
	vec4 vSample3 = texture(g_tInputTexture, vUvTmp3);
	vec4 H_w9m58j = H_taux441 * vSample3;
	vec4 H_018hah = H_oasu0m1 + H_w9m58j;
	float H_idggzm1 = g_vInvTextureDim.x * C_3d0;
	vec2 H_mgfy751 = vec2(H_idggzm1, C_0d0);
	vec2 vUvTmp4 = H_mgfy751 + PS_INPUT_gl_vTexCoord;
	vec4 vSample4 = texture(g_tInputTexture, vUvTmp4);
	vec4 H_47zqjf = H_ka9o0y1 * vSample4;
	vec4 H_oolhdv1 = H_018hah + H_47zqjf;
	vec4 H_y4h59w = vec4(g_flOverbrightAmount);
	vec4 H_49kqo81 = H_oolhdv1 * H_y4h59w;
	vec3 H_159fok1 = H_49kqo81.xyz * H_49kqo81.xyz;
	vec3 H_05yrgx1 = mix(H_49kqo81.xyz, H_159fok1, C_0d8);
	vec4 H_bckx6l1 = H_49kqo81;
	H_bckx6l1.xyz = H_05yrgx1.xyz;
	PS_OUTPUT_gl_vColor = H_bckx6l1;
}
