//ATTRIBMAP-00-50-51-5D-xx
#version 330 core
// LunarGOO output
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_ARB_texture_cube_map_array : enable
#extension GL_ARB_texture_gather : enable
#extension GL_ARB_viewport_array : enable
layout(std140, binding = 14 ) uniform PerViewConstantBuffer_t {
	layout(row_major) mat4 g_matWorldToProjection;
	layout(row_major) mat4 g_matProjectionToWorld;
	layout(row_major) mat4 g_matWorldToView;
	layout(row_major) mat4 g_matViewToProjection;
	vec4 g_vInvProjRow3;
	vec4 g_vClipPlane0;
	float g_flToneMapScalarLinear;
	float g_flLightMapScalar;
	float g_flEnvMapScalar;
	float g_flToneMapScalarGamma;
	vec3 g_vCameraPositionWs;
	float g_flViewportMinZ;
	vec3 g_vCameraDirWs;
	float g_flViewportMaxZ;
	vec3 g_vCameraUpDirWs;
	float g_flTime;
	vec3 g_vDepthPsToVsConversion;
	float g_flNearPlane;
	float g_flFarPlane;
	float g_flLightBinnerFarPlane;
	vec2 g_vInvViewportSize;
	vec2 g_vViewportToGBufferRatio;
	vec2 g_vMorphTextureAtlasSize;
	vec4 g_vInvGBufferSize;
	vec2 g_vViewportOffset;
	vec2 g_vViewportSize;
	vec2 g_vRenderTargetSize;
	float g_flFogBlendToBackground;
	float g_flHenyeyGreensteinCoeff;
	vec3 g_vFogColor;
	float g_flNegFogStartOverFogRange;
	float g_flInvFogRange;
	float g_flFogMaxDensity;
	float g_flFogExponent;
	float g_flMod2xIdentity;
	vec2 g_bRoughnessParams;
	float g_bStereoEnabled;
	float g_flStereoCameraIndex;
	vec3 g_vMiddleEyePositionWs;
	float g_flPad2;
	layout(row_major) mat4 g_matWorldToProjectionMultiview[2];
	vec4 g_vCameraPositionWsMultiview[2];
	vec4 g_vFrameBufferCopyInvSizeAndUvScale;
	vec4 g_vCameraAngles;
	vec4 g_vWorldToCameraOffset;
	vec4 g_vWorldToCameraOffsetMultiview[2];
	vec4 g_vPerViewConstantExtraData0;
	vec4 g_vPerViewConstantExtraData1;
	vec4 g_vPerViewConstantExtraData2;
	vec4 g_vPerViewConstantExtraData3;
} ;
layout(std140, binding = 13 ) uniform _Globals_ {
	vec4 g_vWindStrengthFreqMulHighStrength;
	vec3 g_vWindOffset;
	vec3 g_vWindDir;
	vec3 g_vFadeParams;
} ;
layout( binding = 18 ) uniform sampler2D g_tTransformTexture;
layout( binding = 19 ) uniform sampler2D g_tDensityArray;
layout( binding = 20 ) uniform sampler2D g_tHeightArray;
layout( binding = 21 ) uniform sampler2D g_tSkewBrightness;
layout( binding = 22 ) uniform sampler2D g_tTintArray;
layout(std140, binding = 12 ) uniform GrassParamsPerQuadSlice_t {
	vec4 g_vGrassWidths[8];
	vec4 g_vGrassHeightsMin[8];
	vec4 g_vGrassHeightsMax[8];
	vec4 g_vGrassFlexibilities[8];
	vec4 g_vGrassFlipControls[8];
} ;
layout(std140) uniform DotaGlobalParams_t {
	vec3 g_vGlobalLightDir;
	vec3 g_vGlobalLightColor;
	float g_flGlobalLightSpecularScale;
	vec3 g_vGlobalLightSpecularDir;
	float g_flGlobalLightSpecularExp;
	vec3 g_vGlobalLightSpecularColor;
	float g_flGlobalLightSpecularIndependence;
	vec3 g_vGlobalLightAmbientDir;
	float g_flGlobalLightAmbientScale1;
	vec3 g_vGlobalLightAmbientColor1;
	float g_flGlobalLightAmbientScale2;
	vec3 g_vGlobalLightAmbientColor2;
	float g_flGlobalLightAmbientScale2Hero;
	vec2 g_vGlobalCloud1Offset;
	vec2 g_vGlobalCloud2Offset;
	vec3 g_vFowColor;
	float g_flGlobalCloudScale;
	float g_flFowDarkness;
	float g_flFowGrayFactor;
	float g_flFowColorFactor;
	float g_flFowGrayHilights;
	vec4 g_vFowWorldSize;
	vec4 g_vFowTexOffsets;
	layout(row_major) mat4 g_matShadowWorldToTexture;
	vec4 g_vInvShadowDepthTextureSize;
	vec3 g_vGlobalLightAmbientColor3;
	float g_flGlobalLightAmbientShadowAmount;
} ;
uniform sampler2D g_tFow;
uniform sampler2D g_tFrameBufferCopyTexture;
uniform sampler2D g_tDepthTexture;
uniform sampler2D g_tGBufferAlbedo;
uniform sampler2D g_tGBufferLightingTerms;
uniform sampler2D g_tGBufferDepth;
uniform sampler2D g_tGBufferNormalWs;
layout(std140) uniform PerViewLightingConstantBuffer_t {
	vec4 g_vInvLightTextureDims;
	vec4 g_vLightBinCounts;
	vec2 g_vLowResDeferredLightingTextureDim;
	vec2 g_vLowResDeferredLightingTextureInvDim;
	vec3 g_vToolsAmbientLighting;
	float g_flSSAOEnabled;
	vec3 g_vIrradAtlasInvSize;
	float g_flIrradGlobalLightingFactor;
	vec4 g_vGlobalLightingSHRed;
	vec4 g_vGlobalLightingSHGreen;
	vec4 g_vGlobalLightingSHBlue;
	vec3 g_vRayleighScatteringCoeff;
	float g_flMieScatteringEccentricity;
	vec3 g_vMieScatteringCoeff;
	float g_flMieForwardScatteringRatio;
	vec3 g_vSpecularCubeMapScale;
	float g_flDefaultEnvMapIndex;
	vec4 g_vLightCookieSheetSequenceAndSizes;
	vec3 g_vLpvBoxMinCascade0;
	float g_flLpvBrightnessScale;
	vec3 g_vLpvInvBoxDimCascade0;
	vec2 g_vLpvInvCoeffTextureDim;
} ;
layout(std140) uniform PerLayerConstantBuffer_t {
	vec4 g_vWireframeColor;
} ;
uniform sampler2D g_tClouds;
uniform sampler2DShadow g_tShadowDepthTexture;
layout(location=0) in vec2 VS_INPUT_gl_vPositionOs;
layout(location=1) in vec4 VS_INPUT_gl_vSide_Top_Right;
layout(location=2) in vec4 VS_INPUT_gl_vDensityMask;
layout(location=3) in vec2 VS_INPUT_gl_vTransformTextureUV;
out gl_PerVertex {
	vec4 gl_Position;
	float gl_ClipDistance[1];
} ;
layout(location=0) out vec3 PS_INPUT_gl_vPositionWs;
layout(location=1) out vec3 PS_INPUT_gl_vNormalWs;
layout(location=2) out vec2 PS_INPUT_gl_vTextureCoords;
layout(location=3) out vec3 PS_INPUT_gl_vTint;
layout(location=4) out vec3 PS_INPUT_gl_vBrightnessAlpha;
const float C_0d0 = 0.0;
const ivec2 C_ivec2p1ca0p = ivec2(1, 0);
const ivec2 C_ivec2p2ca0p = ivec2(2, 0);
const ivec2 C_ivec2p3ca0p = ivec2(3, 0);
const float C_0d0136986 = 0.0136986;
const float C_0d00518135 = 0.00518135;
const vec4 C_1t9a5l = vec4(1000000.0);
const vec4 C_vec4p0d0p = vec4(0.0);
const vec4 C_vec4p1d0p = vec4(1.0);
const vec2 C_vec2p2d0p = vec2(2.0);
const vec2 C_vec2pa1d0p = vec2(-1.0);
const float C_a0d5 = -0.5;
const float C_256d0 = 256.0;
const float C_1d0 = 1.0;
const float C_1000000d0 = 1000000.0;
const float C_2d0 = 2.0;
const float C_a1d0 = -1.0;
const float C_0d5 = 0.5;
const vec4 C_onv0px1 = vec4(0.0, 1.0, 2.0, 3.0);
const float C_0d125 = 0.125;
const float C_0d03125 = 0.03125;
const vec3 C_vec3p1d0p = vec3(1.0);
const vec4 C_5dnxfp1 = vec4(0.5, 1.0, 0.5, 1.5);
const vec4 C_vec4p2d0p = vec4(2.0);
const vec4 C_vec4pa1d0p = vec4(-1.0);
const vec4 C_vec4p0d5p = vec4(0.5);
const vec4 C_vec4p3d0p = vec4(3.0);
const vec4 C_gzjq7p = vec4(1.0, 0.5, 0.25, 0.05);
const vec3 C_vec3p0d01p = vec3(0.01);
const vec3 C_imhxe9 = vec3(0.0, 0.0, 1.0);
void main()
{
	gl_ClipDistance[0] = C_0d0;
	vec4 matObjectToWorld = textureLod(g_tTransformTexture, VS_INPUT_gl_vTransformTextureUV, C_0d0);
	vec4 matObjectToWorld1 = textureLodOffset(g_tTransformTexture, VS_INPUT_gl_vTransformTextureUV, C_0d0, C_ivec2p1ca0p);
	vec4 matObjectToWorld2 = textureLodOffset(g_tTransformTexture, VS_INPUT_gl_vTransformTextureUV, C_0d0, C_ivec2p2ca0p);
	vec4 vUStart_VStart_UVScale_GrassQuadU = textureLodOffset(g_tTransformTexture, VS_INPUT_gl_vTransformTextureUV, C_0d0, C_ivec2p3ca0p);
	float H_drg3uf1 = matObjectToWorld.w * C_0d0136986;
	float H_8wctwq = matObjectToWorld1.w * C_0d00518135;
	float flOffset = H_8wctwq + H_drg3uf1;
	vec4 H_7r99yf1 = vec4(flOffset);
	vec4 param = VS_INPUT_gl_vDensityMask * C_1t9a5l;
	vec4 misc3a = clamp(param, C_vec4p0d0p, C_vec4p1d0p);
	vec4 H_zgikec1 = H_7r99yf1 * misc3a;
	vec4 param1 = H_zgikec1 + VS_INPUT_gl_vDensityMask;
	vec4 H_cb84n3 = fract(param1);
	float flFlip = sign(VS_INPUT_gl_vPositionOs.x);
	float vPositionOs = abs(VS_INPUT_gl_vPositionOs.x);
	vec2 H_gcnugl1 = vec2(vPositionOs, VS_INPUT_gl_vPositionOs.y);
	vec2 H_wjf95r1 = H_gcnugl1 * vUStart_VStart_UVScale_GrassQuadU.zz;
	vec2 vDensityCoords = H_wjf95r1 + vUStart_VStart_UVScale_GrassQuadU.xy;
	vec4 vDensity = textureLod(g_tDensityArray, vDensityCoords, C_0d0);
	vec4 flDisplacement = textureLod(g_tHeightArray, vDensityCoords, C_0d0);
	vec4 vSkewBrightness = textureLod(g_tSkewBrightness, vDensityCoords, C_0d0);
	vec2 H_3hmclu1 = vSkewBrightness.xy * C_vec2p2d0p;
	vec2 H_ebj94f1 = H_3hmclu1 + C_vec2pa1d0p;
	vec4 vTint = textureLod(g_tTintArray, vDensityCoords, C_0d0);
	float H_b3k7fi = vPositionOs + C_a0d5;
	float H_5h5m5j1 = H_b3k7fi * C_256d0;
	float H_fv6tdm = C_a0d5 + VS_INPUT_gl_vPositionOs.y;
	float H_exm5lk1 = C_256d0 * H_fv6tdm;
	vec4 vDelta = vDensity - H_cb84n3;
	vec4 H_aaze2j1 = C_1t9a5l * H_cb84n3;
	float flMask = dot(vDelta, H_aaze2j1);
	float misc3a1 = clamp(flMask, C_0d0, C_1d0);
	float param2 = VS_INPUT_gl_vSide_Top_Right.y * C_1000000d0;
	float misc3a2 = clamp(param2, C_0d0, C_1d0);
	vec3 H_7pnklg = vec3(misc3a2);
	int nWidthHeightSlice = int(vUStart_VStart_UVScale_GrassQuadU.w);
	vec4 vHeights = mix(g_vGrassHeightsMin[nWidthHeightSlice], g_vGrassHeightsMax[nWidthHeightSlice], VS_INPUT_gl_vSide_Top_Right.y);
	vec4 misc3a3 = clamp(H_aaze2j1, C_vec4p0d0p, C_vec4p1d0p);
	float misc2a = dot(g_vGrassWidths[nWidthHeightSlice], misc3a3);
	float flBladeWidth = misc2a * misc3a1;
	vec2 H_maz40g = vec2(flBladeWidth);
	float misc2a1 = dot(vHeights, misc3a3);
	float flBladeHeight = misc2a1 * misc3a1;
	vec3 H_gvrnk71 = vec3(flBladeHeight);
	float misc2a2 = dot(g_vGrassFlexibilities[nWidthHeightSlice], misc3a3);
	float flFlexibility = misc2a2 * misc3a1;
	vec3 H_ur7bhv = vec3(flFlexibility);
	float misc2a3 = dot(g_vGrassFlipControls[nWidthHeightSlice], misc3a3);
	float flFlipControl = misc2a3 * misc3a1;
	float flFlip1 = flFlip * flFlipControl;
	vec3 H_g631n = vec3(H_ebj94f1.x, H_ebj94f1.y, C_0d0);
	float dotres = dot(H_g631n, matObjectToWorld.xyz);
	float dotres1 = dot(H_g631n, matObjectToWorld1.xyz);
	float dotres2 = dot(H_g631n, matObjectToWorld2.xyz);
	vec3 H_3cij4j1 = vec3(dotres, dotres1, dotres2);
	vec3 vManualSkew = H_3cij4j1 * g_vFadeParams.zzz;
	float flManualInfluence = length(vManualSkew);
	vec3 H_4qzlat1 = vec3(flManualInfluence);
	float flInvManualInfluence = C_1d0 - flManualInfluence;
	vec3 vManualSkew1 = vManualSkew / H_4qzlat1;
	float H_xuvnee = C_0d0 - vManualSkew1.x;
	float _L = VS_INPUT_gl_vSide_Top_Right.x * C_2d0;
	float H_h09wb3 = _L + C_a1d0;
	float H_s4r27o = H_h09wb3 * C_0d5;
	vec2 H_yy5365 = vec2(H_s4r27o);
	vec2 H_6mxa6t = vec2(vManualSkew1.y, H_xuvnee);
	vec2 H_owiu131 = H_6mxa6t * H_yy5365;
	vec2 H_rrmmph = H_maz40g * H_owiu131;
	vec2 H_cze87u1 = vec2(H_5h5m5j1, H_exm5lk1);
	vec2 H_h2rwlb = H_cze87u1 + H_rrmmph;
	float H_craqzn = flBladeHeight * misc3a2;
	float H_xkwore = H_craqzn * flInvManualInfluence;
	float H_q7wadg1 = H_xkwore + flDisplacement.x;
	float misc2a4 = dot(C_onv0px1, misc3a3);
	float flUV = vUStart_VStart_UVScale_GrassQuadU.w * C_0d125;
	bool H_vn98931 = flFlip1 > C_0d0;
	float H_2uv6q3 = C_1d0 - VS_INPUT_gl_vSide_Top_Right.x;
	float H_3shsb11 = H_2uv6q3 + misc2a4;
	float H_wq42tm = H_3shsb11 * C_0d03125;
	float H_dvlrvu1 = H_wq42tm + flUV;
	vec2 H_g6buzf;
	H_g6buzf.x = H_dvlrvu1;
	float H_iyx2aw1 = VS_INPUT_gl_vSide_Top_Right.x + misc2a4;
	float H_6rfv2o1 = C_0d03125 * H_iyx2aw1;
	float H_s3rhgt1 = H_6rfv2o1 + flUV;
	vec2 H_q4j5iw;
	H_q4j5iw.x = H_s3rhgt1;
	vec2 select = H_vn98931 ? H_g6buzf : H_q4j5iw;
	float H_f5a1k1 = C_1d0 - misc3a2;
	vec2 H_1v5ex4 = select;
	H_1v5ex4.y = H_f5a1k1;
	vec4 H_5r11ss1 = vec4(H_h2rwlb.x, H_h2rwlb.y, H_q7wadg1, C_1d0);
	float dotres3 = dot(H_5r11ss1, matObjectToWorld);
	float dotres4 = dot(H_5r11ss1, matObjectToWorld1);
	float dotres5 = dot(H_5r11ss1, matObjectToWorld2);
	vec3 H_25kyhb = vec3(dotres3, dotres4, dotres5);
	vec3 vDeltaToEye = H_25kyhb - g_vCameraPositionWs;
	float flDistToCamera = length(vDeltaToEye);
	float H_kv9wp7 = flDistToCamera - g_vFadeParams.x;
	float param3 = H_kv9wp7 / g_vFadeParams.y;
	float misc3a4 = clamp(param3, C_0d0, C_1d0);
	float flAlpha = C_1d0 - misc3a4;
	vec3 H_uhrcf51 = vec3(dotres3, dotres4, C_0d0);
	vec3 H_n3n98q = H_uhrcf51 * g_vWindStrengthFreqMulHighStrength.yyy;
	vec3 H_1xub8n = H_n3n98q + g_vWindOffset;
	float vNewPosition = dot(H_1xub8n, C_vec3p1d0p);
	vec4 H_3dhgo21 = vec4(H_1xub8n.x, H_1xub8n.y, H_1xub8n.z, vNewPosition);
	vec4 param4 = H_3dhgo21 * C_5dnxfp1;
	vec4 H_pkik5d1 = fract(param4);
	vec4 H_fwbtkd = H_pkik5d1 * C_vec4p2d0p;
	vec4 vWaves = H_fwbtkd + C_vec4pa1d0p;
	vec4 param5 = vWaves + C_vec4p0d5p;
	vec4 H_gnsyd51 = fract(param5);
	vec4 H_lguk0d1 = C_vec4p2d0p * H_gnsyd51;
	vec4 H_dg1b4n = C_vec4pa1d0p + H_lguk0d1;
	vec4 H_fkyoek1 = abs(H_dg1b4n);
	vec4 H_58tmkq1 = H_fkyoek1 * H_fkyoek1;
	vec4 H_m7ybow1 = C_vec4p2d0p * H_fkyoek1;
	vec4 H_watfs91 = C_vec4p3d0p - H_m7ybow1;
	vec4 H_56ngjf1 = H_58tmkq1 * H_watfs91;
	vec4 vWaves1 = H_56ngjf1 * C_gzjq7p;
	float flAmplitude = dot(vWaves1, C_vec4p1d0p);
	float flAmplitude1 = flAmplitude * g_vWindStrengthFreqMulHighStrength.x;
	vec3 H_vzcajm1 = vec3(flAmplitude1);
	vec3 vSkew = H_vzcajm1 * g_vWindDir;
	vec3 vWindSkew = H_ur7bhv * vSkew;
	vec3 vTotalSkew = mix(vWindSkew, vManualSkew1, flManualInfluence);
	vec3 vTotalSkew1 = H_7pnklg * vTotalSkew;
	vec3 H_9a5gzy1 = H_gvrnk71 * vTotalSkew1;
	vec3 H_vlcw38 = H_25kyhb + H_9a5gzy1;
	vec3 H_es5mfp = H_gvrnk71 * vWindSkew;
	vec3 H_6058ct1 = H_es5mfp * C_vec3p0d01p;
	vec3 vNormal = C_imhxe9 - H_6058ct1;
	vec3 H_81wfcy = vec3(vSkewBrightness.z, flAlpha, C_0d0);
	vec4 H_oh3ua6 = vec4(H_vlcw38.x, H_vlcw38.y, H_vlcw38.z, C_1d0);
	vec4 H_6z94qi = H_oh3ua6 + g_vWorldToCameraOffset;
	float dotres6 = dot(H_6z94qi, g_matWorldToProjection[0]);
	float dotres7 = dot(H_6z94qi, g_matWorldToProjection[1]);
	float dotres8 = dot(H_6z94qi, g_matWorldToProjection[2]);
	float dotres9 = dot(H_6z94qi, g_matWorldToProjection[3]);
	PS_INPUT_gl_vPositionWs = H_vlcw38;
	PS_INPUT_gl_vNormalWs = vNormal;
	PS_INPUT_gl_vTextureCoords = H_1v5ex4;
	PS_INPUT_gl_vTint = vTint.xyz;
	PS_INPUT_gl_vBrightnessAlpha = H_81wfcy;
	float H_q212zt1 = C_0d0 - dotres7;
	float H_8665611 = C_2d0 * dotres8;
	float H_wyecv81 = H_8665611 - dotres9;
	vec4 H_dbr10s1 = vec4(dotres6, H_q212zt1, H_wyecv81, dotres9);
	gl_Position = H_dbr10s1;
}
