//ATTRIBMAP-00-30-50-20-10-5D-xx
#version 330 core
// LunarGOO output
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
layout(std140, binding = 12 ) uniform PerViewConstantBuffer_t {
	layout(row_major) mat4 g_matWorldToProjection;
	layout(row_major) mat4 g_matProjectionToWorld;
	layout(row_major) mat4 g_matWorldToView;
	layout(row_major) mat4 g_matViewToProjection;
	vec4 g_vInvProjRow3;
	vec4 g_vClipPlane0;
	float g_flToneMapScalarLinear;
	float g_flLightMapScalar;
	float g_flEnvMapScalar;
	float g_flToneMapScalarGamma;
	vec3 g_vCameraPositionWs;
	float g_flViewportMinZ;
	vec3 g_vCameraDirWs;
	float g_flViewportMaxZ;
	vec3 g_vCameraUpDirWs;
	float g_flTime;
	vec3 g_vDepthPsToVsConversion;
	float g_flNearPlane;
	float g_flFarPlane;
	float g_flLightBinnerFarPlane;
	vec2 g_vInvViewportSize;
	vec2 g_vViewportToGBufferRatio;
	vec2 g_vMorphTextureAtlasSize;
	vec4 g_vInvGBufferSize;
	vec2 g_vViewportOffset;
	vec2 g_vViewportSize;
	vec2 g_vRenderTargetSize;
	float g_flFogBlendToBackground;
	float g_flHenyeyGreensteinCoeff;
	vec3 g_vFogColor;
	float g_flNegFogStartOverFogRange;
	float g_flInvFogRange;
	float g_flFogMaxDensity;
	float g_flFogExponent;
	float g_flMod2xIdentity;
	vec2 g_bRoughnessParams;
	float g_bStereoEnabled;
	float g_flStereoCameraIndex;
	vec3 g_vMiddleEyePositionWs;
	float g_flPad2;
	layout(row_major) mat4 g_matWorldToProjectionMultiview[2];
	vec4 g_vCameraPositionWsMultiview[2];
	vec4 g_vFrameBufferCopyInvSizeAndUvScale;
	vec4 g_vCameraAngles;
	vec4 g_vWorldToCameraOffset;
	vec4 g_vWorldToCameraOffsetMultiview[2];
	vec4 g_vPerViewConstantExtraData0;
	vec4 g_vPerViewConstantExtraData1;
	vec4 g_vPerViewConstantExtraData2;
	vec4 g_vPerViewConstantExtraData3;
} ;
layout( binding = 18 ) uniform sampler2D g_tTransformTexture;
layout(std140, binding = 13 ) uniform _Globals_ {
	vec2 g_vTexCoordScale;
	vec2 g_vTexCoordOffset;
} ;
layout(std140) uniform DotaGlobalParams_t {
	vec3 g_vGlobalLightDir;
	vec3 g_vGlobalLightColor;
	float g_flGlobalLightSpecularScale;
	vec3 g_vGlobalLightSpecularDir;
	float g_flGlobalLightSpecularExp;
	vec3 g_vGlobalLightSpecularColor;
	float g_flGlobalLightSpecularIndependence;
	vec3 g_vGlobalLightAmbientDir;
	float g_flGlobalLightAmbientScale1;
	vec3 g_vGlobalLightAmbientColor1;
	float g_flGlobalLightAmbientScale2;
	vec3 g_vGlobalLightAmbientColor2;
	float g_flGlobalLightAmbientScale2Hero;
	vec2 g_vGlobalCloud1Offset;
	vec2 g_vGlobalCloud2Offset;
	vec3 g_vFowColor;
	float g_flGlobalCloudScale;
	float g_flFowDarkness;
	float g_flFowGrayFactor;
	float g_flFowColorFactor;
	float g_flFowGrayHilights;
	vec4 g_vFowWorldSize;
	vec4 g_vFowTexOffsets;
	layout(row_major) mat4 g_matShadowWorldToTexture;
	vec4 g_vInvShadowDepthTextureSize;
	vec3 g_vGlobalLightAmbientColor3;
	float g_flGlobalLightAmbientShadowAmount;
} ;
uniform sampler2D g_tFow;
uniform sampler2D g_tFrameBufferCopyTexture;
uniform sampler2D g_tDepthTexture;
uniform sampler2D g_tGBufferAlbedo;
uniform sampler2D g_tGBufferLightingTerms;
uniform sampler2D g_tGBufferDepth;
uniform sampler2D g_tGBufferNormalWs;
layout(std140) uniform PerViewLightingConstantBuffer_t {
	vec4 g_vInvLightTextureDims;
	vec4 g_vLightBinCounts;
	vec2 g_vLowResDeferredLightingTextureDim;
	vec2 g_vLowResDeferredLightingTextureInvDim;
	vec3 g_vToolsAmbientLighting;
	float g_flSSAOEnabled;
	vec3 g_vIrradAtlasInvSize;
	float g_flIrradGlobalLightingFactor;
	vec4 g_vGlobalLightingSHRed;
	vec4 g_vGlobalLightingSHGreen;
	vec4 g_vGlobalLightingSHBlue;
	vec3 g_vRayleighScatteringCoeff;
	float g_flMieScatteringEccentricity;
	vec3 g_vMieScatteringCoeff;
	float g_flMieForwardScatteringRatio;
	vec3 g_vSpecularCubeMapScale;
	float g_flDefaultEnvMapIndex;
	vec4 g_vLightCookieSheetSequenceAndSizes;
	vec3 g_vLpvBoxMinCascade0;
	float g_flLpvBrightnessScale;
	vec3 g_vLpvInvBoxDimCascade0;
	vec2 g_vLpvInvCoeffTextureDim;
} ;
layout(std140) uniform PerLayerConstantBuffer_t {
	vec4 g_vWireframeColor;
} ;
uniform sampler2D g_tClouds;
uniform sampler2DShadow g_tShadowDepthTexture;
layout(location=0) in vec3 VS_INPUT_gl_vPositionOs;
layout(location=1) in vec4 VS_INPUT_gl_vNormalOs;
layout(location=2) in vec2 VS_INPUT_gl_vTexCoord;
layout(location=3) in uvec4 VS_INPUT_gl_vBlendIndices;
layout(location=4) in vec4 VS_INPUT_gl_vBlendWeight;
layout(location=5) in vec2 VS_INPUT_gl_vTransformTextureUV;
out gl_PerVertex {
	vec4 gl_Position;
	float gl_ClipDistance[1];
} ;
layout(location=0) out vec2 PS_INPUT_gl_vBaseTexCoord;
const float C_0d0 = 0.0;
const int C_2 = 2;
const int C_8 = 8;
const float C_0d5 = 0.5;
const ivec2 C_ivec2p2ca0p = ivec2(2, 0);
const ivec2 C_ivec2p1ca0p = ivec2(1, 0);
const float C_1d0 = 1.0;
const float C_2d0 = 2.0;
void main()
{
	gl_ClipDistance[0] = C_0d0;
	int H_iu02zk1 = ivec4(VS_INPUT_gl_vBlendIndices).x << C_2;
	int H_pusuqs1 = H_iu02zk1 + C_8;
	float H_nwbnx31 = float(H_pusuqs1);
	float H_tmfqxf = H_nwbnx31 + C_0d5;
	float H_pik68t = H_tmfqxf * g_vInvGBufferSize.z;
	vec2 H_5f7u4m1 = vec2(H_pik68t, C_0d0);
	vec2 vBlendTransform0UV = H_5f7u4m1 + VS_INPUT_gl_vTransformTextureUV;
	float flWrapLines = floor(vBlendTransform0UV.x);
	float H_7mdp57 = vBlendTransform0UV.x - flWrapLines;
	float H_wgm8gx = flWrapLines * g_vInvGBufferSize.w;
	float H_06afd41 = H_wgm8gx + vBlendTransform0UV.y;
	vec2 H_crnj9e1 = vec2(H_7mdp57, H_06afd41);
	vec4 vMatObjectToWorldRow = textureLodOffset(g_tTransformTexture, H_crnj9e1, C_0d0, C_ivec2p2ca0p);
	vec4 vMatObjectToWorldRow1 = textureLodOffset(g_tTransformTexture, H_crnj9e1, C_0d0, C_ivec2p1ca0p);
	vec4 vMatObjectToWorldRow2 = textureLod(g_tTransformTexture, H_crnj9e1, C_0d0);
	vec4 vMatObjectToWorldRow3 = VS_INPUT_gl_vBlendWeight.xxxx * vMatObjectToWorldRow;
	vec4 vMatObjectToWorldRow4 = VS_INPUT_gl_vBlendWeight.xxxx * vMatObjectToWorldRow1;
	vec4 vMatObjectToWorldRow5 = VS_INPUT_gl_vBlendWeight.xxxx * vMatObjectToWorldRow2;
	int H_vwqhmc = ivec4(VS_INPUT_gl_vBlendIndices).y << C_2;
	int H_bheuh8 = C_8 + H_vwqhmc;
	float H_1y0o031 = float(H_bheuh8);
	float H_p432w41 = C_0d5 + H_1y0o031;
	float H_oos4t = H_p432w41 * g_vInvGBufferSize.z;
	vec2 H_0tllf5 = vec2(H_oos4t, C_0d0);
	vec2 vBlendTransform0UV1 = H_0tllf5 + VS_INPUT_gl_vTransformTextureUV;
	float flWrapLines1 = floor(vBlendTransform0UV1.x);
	float H_lbkazl1 = vBlendTransform0UV1.x - flWrapLines1;
	float H_bgf3c8 = flWrapLines1 * g_vInvGBufferSize.w;
	float H_yyulap1 = H_bgf3c8 + vBlendTransform0UV1.y;
	vec2 H_sg29b2 = vec2(H_lbkazl1, H_yyulap1);
	vec4 H_tmwdli1 = vec4(VS_INPUT_gl_vBlendWeight.y);
	vec4 vMatObjectToWorldRow6 = textureLod(g_tTransformTexture, H_sg29b2, C_0d0);
	vec4 H_svdh2 = H_tmwdli1 * vMatObjectToWorldRow6;
	vec4 vMatObjectToWorldRow7 = H_svdh2 + vMatObjectToWorldRow5;
	vec4 vTmp = textureLodOffset(g_tTransformTexture, H_sg29b2, C_0d0, C_ivec2p1ca0p);
	vec4 vTmp1 = textureLodOffset(g_tTransformTexture, H_sg29b2, C_0d0, C_ivec2p2ca0p);
	vec4 H_jid0w8 = H_tmwdli1 * vTmp;
	vec4 vMatObjectToWorldRow8 = H_jid0w8 + vMatObjectToWorldRow4;
	vec4 H_usujrj1 = H_tmwdli1 * vTmp1;
	vec4 vMatObjectToWorldRow9 = H_usujrj1 + vMatObjectToWorldRow3;
	vec4 vAnimationControlWord = textureLod(g_tTransformTexture, VS_INPUT_gl_vTransformTextureUV, C_0d0);
	vec3 H_u8espd = VS_INPUT_gl_vPositionOs * vAnimationControlWord.zzz;
	vec4 H_2f7gnb = vec4(H_u8espd.x, H_u8espd.y, H_u8espd.z, C_1d0);
	float dotres = dot(H_2f7gnb, vMatObjectToWorldRow7);
	float dotres1 = dot(H_2f7gnb, vMatObjectToWorldRow8);
	float dotres2 = dot(H_2f7gnb, vMatObjectToWorldRow9);
	vec2 H_wgjrmr = VS_INPUT_gl_vTexCoord * g_vTexCoordScale;
	vec2 H_pauxoy1 = H_wgjrmr + g_vTexCoordOffset;
	vec4 H_vokf33 = vec4(dotres, dotres1, dotres2, C_1d0);
	vec4 H_a5xsfe = H_vokf33 + g_vWorldToCameraOffset;
	float dotres3 = dot(H_a5xsfe, g_matWorldToProjection[0]);
	float dotres4 = dot(H_a5xsfe, g_matWorldToProjection[1]);
	float dotres5 = dot(H_a5xsfe, g_matWorldToProjection[2]);
	float dotres6 = dot(H_a5xsfe, g_matWorldToProjection[3]);
	PS_INPUT_gl_vBaseTexCoord = H_pauxoy1;
	float H_rdf2pt1 = C_0d0 - dotres4;
	float H_rrbnew1 = dotres5 * C_2d0;
	float H_36c2hm1 = H_rrbnew1 - dotres6;
	vec4 H_6n8lpq1 = vec4(dotres3, H_rdf2pt1, H_36c2hm1, dotres6);
	gl_Position = H_6n8lpq1;
}
