//ATTRIBMAP-50-51-90-53-54-55-56-57-91-xx
#version 330 core
// LunarGOO output
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
struct VS_INPUT {
	vec2 member0;
	vec4 member1;
	vec4 member2;
	vec4 member3;
	vec4 member4;
	vec4 member5;
	vec4 member6;
	vec4 member7;
	vec4 member8;
};
layout(std140, binding = 14 ) uniform PerViewConstantBuffer_t {
	layout(row_major) mat4 g_matWorldToProjection;
	layout(row_major) mat4 g_matProjectionToWorld;
	layout(row_major) mat4 g_matWorldToView;
	layout(row_major) mat4 g_matViewToProjection;
	vec4 g_vInvProjRow3;
	vec4 g_vClipPlane0;
	float g_flToneMapScalarLinear;
	float g_flLightMapScalar;
	float g_flEnvMapScalar;
	float g_flToneMapScalarGamma;
	vec3 g_vCameraPositionWs;
	float g_flViewportMinZ;
	vec3 g_vCameraDirWs;
	float g_flViewportMaxZ;
	vec3 g_vCameraUpDirWs;
	float g_flTime;
	vec3 g_vDepthPsToVsConversion;
	float g_flNearPlane;
	float g_flFarPlane;
	float g_flLightBinnerFarPlane;
	vec2 g_vInvViewportSize;
	vec2 g_vViewportToGBufferRatio;
	vec2 g_vMorphTextureAtlasSize;
	vec4 g_vInvGBufferSize;
	vec2 g_vViewportOffset;
	vec2 g_vViewportSize;
	vec2 g_vRenderTargetSize;
	float g_flFogBlendToBackground;
	float g_flHenyeyGreensteinCoeff;
	vec3 g_vFogColor;
	float g_flNegFogStartOverFogRange;
	float g_flInvFogRange;
	float g_flFogMaxDensity;
	float g_flFogExponent;
	float g_flMod2xIdentity;
	vec2 g_bRoughnessParams;
	float g_bStereoEnabled;
	float g_flStereoCameraIndex;
	vec3 g_vMiddleEyePositionWs;
	float g_flPad2;
	layout(row_major) mat4 g_matWorldToProjectionMultiview[2];
	vec4 g_vCameraPositionWsMultiview[2];
	vec4 g_vFrameBufferCopyInvSizeAndUvScale;
	vec4 g_vCameraAngles;
	vec4 g_vWorldToCameraOffset;
	vec4 g_vWorldToCameraOffsetMultiview[2];
	vec4 g_vPerViewConstantExtraData0;
	vec4 g_vPerViewConstantExtraData1;
	vec4 g_vPerViewConstantExtraData2;
	vec4 g_vPerViewConstantExtraData3;
} ;
layout(std140, binding = 13 ) uniform SpritecardVertexControls_t {
	vec4 g_vecRadiusControls;
	vec4 g_vecExtraData;
	vec4 g_vecSequenceAddressingControls;
	vec4 g_vecDepthControlAndRotationCenterData;
	vec4 g_vecOrientationFadeControlData;
	vec4 g_vecTexelSizeControls;
	vec4 g_vecFinalUVOffsetAndScale;
	vec4 g_vecExtraData2;
} ;
layout(std140, binding = 12 ) uniform SpritecardSheetData_t {
	vec4 g_vSheetDataIndex;
} ;
layout( binding = 18 ) uniform sampler2D g_tParticleSheetTexture;
layout(std140, binding = 15 ) uniform SpriteCardPixelControls_t {
	vec4 g_vecPixelControls;
	vec4 g_vecBlendControl;
	vec4 g_vRefractControl;
	vec4 g_vecSeq0Scale;
	vec4 g_vecSeq0Bias;
	vec4 g_vecSeq0AlphaBlendControl;
	vec4 g_vecSeq1Scale;
	vec4 g_vecSeq1Bias;
	vec4 g_vecSeq1AlphaBlendControl;
	vec4 g_vecMotionVectorsControl;
	vec4 g_vColorTransformScale;
	float g_flColorTransformAlphaBias;
	float g_flDesatAmount;
	vec2 _g_vPadding_;
	vec4 g_vecOutlineColor;
	vec4 g_vecOutlineRanges;
	vec4 g_vecHSVShiftShadowDensity;
} ;
layout(std140) uniform DotaGlobalParams_t {
	vec3 g_vGlobalLightDir;
	vec3 g_vGlobalLightColor;
	float g_flGlobalLightSpecularScale;
	vec3 g_vGlobalLightSpecularDir;
	float g_flGlobalLightSpecularExp;
	vec3 g_vGlobalLightSpecularColor;
	float g_flGlobalLightSpecularIndependence;
	vec3 g_vGlobalLightAmbientDir;
	float g_flGlobalLightAmbientScale1;
	vec3 g_vGlobalLightAmbientColor1;
	float g_flGlobalLightAmbientScale2;
	vec3 g_vGlobalLightAmbientColor2;
	float g_flGlobalLightAmbientScale2Hero;
	vec2 g_vGlobalCloud1Offset;
	vec2 g_vGlobalCloud2Offset;
	vec3 g_vFowColor;
	float g_flGlobalCloudScale;
	float g_flFowDarkness;
	float g_flFowGrayFactor;
	float g_flFowColorFactor;
	float g_flFowGrayHilights;
	vec4 g_vFowWorldSize;
	vec4 g_vFowTexOffsets;
	layout(row_major) mat4 g_matShadowWorldToTexture;
	vec4 g_vInvShadowDepthTextureSize;
	vec3 g_vGlobalLightAmbientColor3;
	float g_flGlobalLightAmbientShadowAmount;
} ;
uniform sampler2D g_tFow;
uniform sampler2D g_tFrameBufferCopyTexture;
uniform sampler2D g_tDepthTexture;
uniform sampler2D g_tGBufferAlbedo;
uniform sampler2D g_tGBufferLightingTerms;
uniform sampler2D g_tGBufferDepth;
uniform sampler2D g_tGBufferNormalWs;
layout(std140) uniform PerViewLightingConstantBuffer_t {
	vec4 g_vInvLightTextureDims;
	vec4 g_vLightBinCounts;
	vec2 g_vLowResDeferredLightingTextureDim;
	vec2 g_vLowResDeferredLightingTextureInvDim;
	vec3 g_vToolsAmbientLighting;
	float g_flSSAOEnabled;
	vec3 g_vIrradAtlasInvSize;
	float g_flIrradGlobalLightingFactor;
	vec4 g_vGlobalLightingSHRed;
	vec4 g_vGlobalLightingSHGreen;
	vec4 g_vGlobalLightingSHBlue;
	vec3 g_vRayleighScatteringCoeff;
	float g_flMieScatteringEccentricity;
	vec3 g_vMieScatteringCoeff;
	float g_flMieForwardScatteringRatio;
	vec3 g_vSpecularCubeMapScale;
	float g_flDefaultEnvMapIndex;
	vec4 g_vLightCookieSheetSequenceAndSizes;
	vec3 g_vLpvBoxMinCascade0;
	float g_flLpvBrightnessScale;
	vec3 g_vLpvInvBoxDimCascade0;
	vec2 g_vLpvInvCoeffTextureDim;
} ;
layout(std140) uniform PerLayerConstantBuffer_t {
	vec4 g_vWireframeColor;
} ;
layout(std140) uniform SpritecardNormalSheetData_t {
	vec4 g_vNormalSheetDataIndex;
} ;
layout(std140) uniform SpritecardMotionVectorsSheetData_t {
	vec4 g_vMotionVectorsSheetDataIndex;
} ;
uniform sampler2D g_tBaseTexture;
uniform sampler2D g_tBaseTextureNoSRGB;
uniform sampler2D g_tClouds;
uniform sampler2DShadow g_tShadowDepthTexture;
layout(location=0) in vec2 VS_INPUT_gl_m_vCornerID;
layout(location=1) in vec4 VS_INPUT_gl_m_vSequenceAndTimeData;
layout(location=2) in vec4 VS_INPUT_gl_m_vTint;
layout(location=3) in vec4 VS_INPUT_gl_m_vPosAndRadius0;
layout(location=4) in vec4 VS_INPUT_gl_m_vPosAndRadius1;
layout(location=5) in vec4 VS_INPUT_gl_m_vPosAndRadius2;
layout(location=6) in vec4 VS_INPUT_gl_m_vPosAndRadius3;
layout(location=7) in vec4 VS_INPUT_gl_m_vCropDomain;
layout(location=8) in vec4 VS_INPUT_gl_m_vTint1;
out gl_PerVertex {
	vec4 gl_Position;
	float gl_ClipDistance[1];
} ;
layout(location=0) out vec4 PS_INPUT_gl_m_vTexCoords;
layout(location=1) out vec4 PS_INPUT_gl_m_vTintColor;
layout(location=2) out vec4 PS_INPUT_gl_vPositionWs_flLinearDepth;
layout(location=3) out vec3 PS_INPUT_gl_vNormalWs;
layout(location=4) out vec4 PS_INPUT_gl_m_vAnimationBlendValues;
const float C_0d0 = 0.0;
const vec2 C_vec2p2d0p = vec2(2.0);
const vec2 C_vec2pa1d0p = vec2(-1.0);
const float C_0d5 = 0.5;
const float C_1d0 = 1.0;
const float C_a0d5 = -0.5;
const float C_3d0 = 3.0;
const vec2 C_a1z03r = vec2(0.0, 0.0);
const float C_2d0 = 2.0;
const float C_a2d0 = -2.0;
const vec4 C_vec4pa0d5p = vec4(-0.5);
const vec4 C_vec4p0d5p = vec4(0.5);
const vec4 C_vec4p2d0p = vec4(2.0);
const vec2 C_vec2p0d0p = vec2(0.0);
const vec2 C_vec2p1d0p = vec2(1.0);
const vec3 C_vec3p12d92p = vec3(12.92);
const vec3 C_vec3p1d055p = vec3(1.055);
const vec3 C_bw96as = vec3(0.0521327);
const vec3 C_vec3p2d4p = vec3(2.4);
const float C_0d04045 = 0.04045;
const float C_a3d0 = -3.0;
const float C_a5d0 = -5.0;
const float C_4d0 = 4.0;
const float C_5d0 = 5.0;
const vec4 C_vec4p0d0p = vec4(0.0);
const float C_0d001 = 0.001;
const vec3 C_vec3p0d0p = vec3(0.0);
void main()
{
	vec4 param;
	float param1;
	VS_INPUT param2;
	VS_INPUT param3;
	VS_INPUT mainIn;
	mainIn.member0 = VS_INPUT_gl_m_vCornerID;
	mainIn.member1 = VS_INPUT_gl_m_vSequenceAndTimeData;
	mainIn.member2 = VS_INPUT_gl_m_vTint;
	mainIn.member3 = VS_INPUT_gl_m_vPosAndRadius0;
	mainIn.member4 = VS_INPUT_gl_m_vPosAndRadius1;
	mainIn.member5 = VS_INPUT_gl_m_vPosAndRadius2;
	mainIn.member6 = VS_INPUT_gl_m_vPosAndRadius3;
	mainIn.member7 = VS_INPUT_gl_m_vCropDomain;
	mainIn.member8 = VS_INPUT_gl_m_vTint1;
	gl_ClipDistance[0] = C_0d0;
	vec2 H_x3n5dv1 = mainIn.member7.zw * C_vec2p2d0p;
	vec2 vFlip = H_x3n5dv1 + C_vec2pa1d0p;
	vec2 vCornerCoords = mainIn.member0 * vFlip;
	float H_v1fmof = vCornerCoords.x * C_0d5;
	float H_yuxxyt = C_1d0 - mainIn.member7.x;
	float H_3q8ngg = H_v1fmof * H_yuxxyt;
	float H_kl1lkh1 = C_0d5 + H_3q8ngg;
	float H_7ttbnz = vCornerCoords.y * C_a0d5;
	float H_xjjx8u = C_1d0 - mainIn.member7.y;
	float H_3jiog11 = H_7ttbnz * H_xjjx8u;
	float H_0zvieu = C_0d5 + H_3jiog11;
	vec4 H_qex72y = vec4(H_kl1lkh1, H_0zvieu, H_kl1lkh1, H_0zvieu);
	float H_fz8gko1 = C_1d0 / g_vSheetDataIndex.y;
	float param4 = mainIn.member1.x - g_vSheetDataIndex.w;
	bool H_00cv0b1 = param4 < C_0d0;
	float phitmp = mainIn.member1.x * C_3d0;
	float select = H_00cv0b1 ? phitmp : C_0d0;
	float H_0ql1v01 = g_vSheetDataIndex.z * select;
	float H_jf16um = H_0ql1v01 + g_vSheetDataIndex.x;
	vec2 H_23b4ob1 = C_a1z03r;
	H_23b4ob1.y = H_jf16um;
	vec4 vecSequenceControlData = textureLod(g_tParticleSheetTexture, H_23b4ob1, C_0d0);
	float H_8sap0s = C_0d5 * g_vSheetDataIndex.y;
	float H_4qgoji = H_8sap0s * mainIn.member1.z;
	float flSequenceIndexingTime = H_4qgoji * g_vecSequenceAddressingControls.x;
	float H_i2zja7 = fract(flSequenceIndexingTime);
	float flTexFrameIndex = floor(flSequenceIndexingTime);
	float flTexFrameIndex1 = flTexFrameIndex * C_2d0;
	bool H_ddp27s1 = vecSequenceControlData.z > C_0d0;
	float param5 = g_vSheetDataIndex.y + C_a2d0;
	float misc2a = min(param5, flTexFrameIndex1);
	float H_1o68ll1 = mod(flTexFrameIndex1, g_vSheetDataIndex.y);
	float select1 = H_ddp27s1 ? misc2a : H_1o68ll1;
	float flTexFrameIndex2 = H_fz8gko1 * select1;
	vec2 H_k06g5s1 = vec2(flTexFrameIndex2, H_jf16um);
	vec4 vFrameControlData = textureLod(g_tParticleSheetTexture, H_k06g5s1, C_0d0);
	float H_bhjmxk = mix(vFrameControlData.x, vFrameControlData.w, H_i2zja7);
	float H_9hsm8w = H_jf16um + g_vSheetDataIndex.z;
	vec2 H_nhdvv4 = vec2(flTexFrameIndex2, H_9hsm8w);
	vec4 H_7wi6px1 = textureLod(g_tParticleSheetTexture, H_nhdvv4, C_0d0);
	float H_k46du = C_2d0 * g_vSheetDataIndex.z;
	float H_7qkvko = H_jf16um + H_k46du;
	vec2 H_qwhub91 = vec2(flTexFrameIndex2, H_7qkvko);
	vec4 H_409qyl1 = textureLod(g_tParticleSheetTexture, H_qwhub91, C_0d0);
	float H_7w4koi1 = H_fz8gko1 + flTexFrameIndex2;
	vec2 H_s1uajz = vec2(H_7w4koi1, H_9hsm8w);
	vec4 H_f1zua7 = textureLod(g_tParticleSheetTexture, H_s1uajz, C_0d0);
	vec2 vCroppedSize = H_f1zua7.zw - H_f1zua7.xy;
	vec2 H_ico401 = H_7wi6px1.zw - H_7wi6px1.xy;
	vec2 vUncroppedSize = H_ico401 / vCroppedSize;
	vec2 H_wgxaqh = H_f1zua7.xy * vUncroppedSize;
	vec2 H_bdpy9p1 = H_7wi6px1.xy - H_wgxaqh;
	vec2 H_7itzqn = H_bdpy9p1 + vUncroppedSize;
	vec2 H_u6lrps1 = H_409qyl1.zw - H_409qyl1.xy;
	vec2 vUncroppedSize1 = H_u6lrps1 / vCroppedSize;
	vec2 H_zscsvo = H_f1zua7.xy * vUncroppedSize1;
	vec2 H_vcjwrl1 = H_409qyl1.xy - H_zscsvo;
	vec2 H_49nf3d1 = H_vcjwrl1 + vUncroppedSize1;
	float param6 = C_1d0 / g_vecSequenceAddressingControls.z;
	float misc3a = clamp(param6, C_0d0, C_1d0);
	vec4 H_kd1ous = vec4(misc3a);
	vec4 H_n04bl11 = H_qex72y + C_vec4pa0d5p;
	vec4 H_szwqor1 = H_kd1ous * H_n04bl11;
	vec4 vZoomedUVs = H_szwqor1 + C_vec4p0d5p;
	float H_z9n5hl = C_0d5 * H_bhjmxk;
	float H_4ty8x61 = C_0d5 + H_z9n5hl;
	vec4 H_y1ofkt1 = vec4(H_4ty8x61, H_4ty8x61, H_z9n5hl, H_z9n5hl);
	vec4 vLerpedValue = mix(H_qex72y, vZoomedUVs, H_y1ofkt1);
	float H_bv8qvl = g_vecFinalUVOffsetAndScale.z * vLerpedValue.x;
	float H_33kuvq = H_bv8qvl + g_vecFinalUVOffsetAndScale.x;
	float H_tg3onf1 = g_vecFinalUVOffsetAndScale.w * vLerpedValue.y;
	float H_l5gf1j1 = H_tg3onf1 + g_vecFinalUVOffsetAndScale.y;
	float H_99gpfm = g_vecFinalUVOffsetAndScale.z * vLerpedValue.z;
	float H_cs9wd5 = H_99gpfm + g_vecFinalUVOffsetAndScale.x;
	float H_7rntrb1 = g_vecFinalUVOffsetAndScale.w * vLerpedValue.w;
	float H_dqz5sk = H_7rntrb1 + g_vecFinalUVOffsetAndScale.y;
	vec4 H_2wsz46 = vec4(H_33kuvq, H_l5gf1j1, H_cs9wd5, H_dqz5sk);
	vec4 vDeltaUV = g_vecFinalUVOffsetAndScale.xyxy - H_2wsz46;
	vec4 vDeltaUV1 = vDeltaUV * C_vec4p2d0p;
	vec4 vDeltaUV2 = g_vecFinalUVOffsetAndScale.zwzw + vDeltaUV1;
	bool H_cev5er = vDeltaUV2.x < C_0d0;
	float H_hfcrim = H_cev5er ? H_f1zua7.z : H_f1zua7.x;
	bool H_nc5hii1 = vDeltaUV2.y < C_0d0;
	float vTestCorner = H_nc5hii1 ? C_1d0 : C_0d0;
	vec2 H_t86n621 = vec2(H_hfcrim, vTestCorner);
	vec2 H_vulic1 = vec2(H_33kuvq, H_l5gf1j1);
	vec2 H_3b3i331 = H_t86n621 - H_vulic1;
	vec2 param7 = H_3b3i331 / vDeltaUV2.xy;
	vec2 misc3a1 = clamp(param7, C_vec2p0d0p, C_vec2p1d0p);
	vec4 H_jn1u79 = misc3a1.xyxy * vDeltaUV2;
	vec4 vSeq0LocalCornerUVs = H_2wsz46 + H_jn1u79;
	vec2 H_2uuij31 = H_7itzqn - H_bdpy9p1;
	vec2 H_5uk7ab1 = H_2uuij31 * vSeq0LocalCornerUVs.xy;
	vec2 H_bzuja31 = H_5uk7ab1 + H_bdpy9p1;
	vec2 H_iroh6h1 = H_49nf3d1 - H_vcjwrl1;
	vec2 H_rpare7 = H_iroh6h1 * vSeq0LocalCornerUVs.zw;
	vec2 H_mxht6l1 = H_rpare7 + H_vcjwrl1;
	vec3 vLinearSegment = mainIn.member2.xyz / C_vec3p12d92p;
	vec3 H_5wer1f1 = mainIn.member2.xyz / C_vec3p1d055p;
	vec3 H_ctvgtv1 = H_5wer1f1 + C_bw96as;
	vec3 vExpSegment = pow(H_ctvgtv1, C_vec3p2d4p);
	bool H_0rpnph = mainIn.member2.x > C_0d04045;
	float select2 = H_0rpnph ? vExpSegment.x : vLinearSegment.x;
	bool H_rh3dd11 = mainIn.member2.y > C_0d04045;
	float select3 = H_rh3dd11 ? vExpSegment.y : vLinearSegment.y;
	bool H_y1yyma1 = mainIn.member2.z > C_0d04045;
	float select4 = H_y1yyma1 ? vExpSegment.z : vLinearSegment.z;
	vec4 H_s3ygu61 = vec4(select2, select3, select4, mainIn.member2.w);
	vec4 vecTint = mix(mainIn.member2, H_s3ygu61, g_vecExtraData2.x);
	float H_jzvcmi = C_0d5 * mainIn.member0.y;
	float flT = C_0d5 + H_jzvcmi;
	float H_le24y71 = flT * flT;
	float tSqr = C_0d5 * H_le24y71;
	float tSqrSqr = flT * tSqr;
	float H_2dc6ux1 = C_0d5 * flT;
	float param8 = C_0d0 - tSqrSqr;
	float H_pytl76 = mainIn.member3.x * param8;
	float H_szisgc1 = mainIn.member3.y * param8;
	float H_z2gwxr = mainIn.member3.z * param8;
	float param9 = C_3d0 * tSqrSqr;
	float H_hjny17 = mainIn.member4.x * param9;
	float H_om1thx = mainIn.member4.y * param9;
	float H_7nce4o = mainIn.member4.z * param9;
	float parama = tSqrSqr * C_a3d0;
	float H_09armi = mainIn.member5.x * parama;
	float H_5v0sx01 = mainIn.member5.y * parama;
	float H_6tfk101 = mainIn.member5.z * parama;
	float H_9tzyi41 = mainIn.member6.x * tSqrSqr;
	float H_a400ur1 = mainIn.member6.y * tSqrSqr;
	float H_fakfa2 = mainIn.member6.z * tSqrSqr;
	float H_lvkwgf1 = H_hjny17 + H_pytl76;
	float H_tmvnk4 = H_om1thx + H_szisgc1;
	float H_awe2q1 = H_7nce4o + H_z2gwxr;
	float H_8pqbuq = H_09armi + H_lvkwgf1;
	float H_dimrv1 = H_5v0sx01 + H_tmvnk4;
	float H_qwnzje = H_6tfk101 + H_awe2q1;
	float H_jghmtm = H_8pqbuq + H_9tzyi41;
	float H_kzca0c = H_a400ur1 + H_dimrv1;
	float H_q54yoc = H_fakfa2 + H_qwnzje;
	float paramb = C_2d0 * tSqr;
	float H_fpxc5p1 = mainIn.member3.x * paramb;
	float H_m4ub4o1 = mainIn.member3.y * paramb;
	float H_hmwhyc = mainIn.member3.z * paramb;
	float paramc = tSqr * C_a5d0;
	float H_fwjjlh = mainIn.member4.x * paramc;
	float H_62atgm1 = mainIn.member4.y * paramc;
	float H_5366p4 = mainIn.member4.z * paramc;
	float paramd = tSqr * C_4d0;
	float H_36hssh = mainIn.member5.x * paramd;
	float H_2ytqr11 = mainIn.member5.y * paramd;
	float H_9qml7z = mainIn.member5.z * paramd;
	float parame = C_0d0 - tSqr;
	float H_70chly = mainIn.member6.x * parame;
	float H_mhx0uv1 = mainIn.member6.y * parame;
	float H_ha7arg = mainIn.member6.z * parame;
	float H_e0ad5s = H_fpxc5p1 + H_jghmtm;
	float H_wdx7bs1 = H_kzca0c + H_m4ub4o1;
	float H_d2uq3v1 = H_hmwhyc + H_q54yoc;
	float H_xmjmd6 = H_e0ad5s + H_fwjjlh;
	float H_ythhlk = H_62atgm1 + H_wdx7bs1;
	float H_ukijr6 = H_5366p4 + H_d2uq3v1;
	float H_roh3s21 = H_36hssh + H_xmjmd6;
	float H_get1wg = H_2ytqr11 + H_ythhlk;
	float H_nc4wpy = H_9qml7z + H_ukijr6;
	float H_zio63k1 = H_70chly + H_roh3s21;
	float H_imr8c7 = H_get1wg + H_mhx0uv1;
	float H_3hmao11 = H_ha7arg + H_nc4wpy;
	float paramf = C_0d0 - H_2dc6ux1;
	float H_bhcb9q1 = mainIn.member3.x * paramf;
	float H_iw8a8p1 = mainIn.member3.y * paramf;
	float H_debg2e = mainIn.member3.z * paramf;
	float H_24emrw = H_2dc6ux1 * mainIn.member5.x;
	float H_1tzl1x = H_2dc6ux1 * mainIn.member5.y;
	float H_4q6n7w = H_2dc6ux1 * mainIn.member5.z;
	float H_f3qgvs1 = H_bhcb9q1 + H_zio63k1;
	float H_2qn6x1 = H_imr8c7 + H_iw8a8p1;
	float H_j6v8ad = H_3hmao11 + H_debg2e;
	float H_yaxsxf = H_24emrw + H_f3qgvs1;
	float H_unagxr1 = H_1tzl1x + H_2qn6x1;
	float H_qx65ru1 = H_4q6n7w + H_j6v8ad;
	float H_wu8a6o = H_yaxsxf + mainIn.member4.x;
	float H_gxzgo5 = H_unagxr1 + mainIn.member4.y;
	float H_xz3y4g = H_qx65ru1 + mainIn.member4.z;
	vec3 H_3v83rp = vec3(H_wu8a6o, H_gxzgo5, H_xz3y4g);
	float H_swv8pv = C_3d0 * flT;
	float H_6bkgrp1 = H_swv8pv * flT;
	float tOne = C_0d5 * H_6bkgrp1;
	float H_37dwlc1 = C_2d0 * flT;
	float tTwo = C_0d5 * H_37dwlc1;
	float paramg = C_0d0 - tOne;
	float H_csqbzp1 = mainIn.member3.x * paramg;
	float H_hlu9ip1 = mainIn.member3.y * paramg;
	float H_eppgsd = mainIn.member3.z * paramg;
	float paramh = C_3d0 * tOne;
	float H_65zf3k = mainIn.member4.x * paramh;
	float H_ftuwyj1 = mainIn.member4.y * paramh;
	float H_ggjan1 = mainIn.member4.z * paramh;
	float parami = C_a3d0 * tOne;
	float H_8pgueg = mainIn.member5.x * parami;
	float H_db7vpy = mainIn.member5.y * parami;
	float H_e9mntx = mainIn.member5.z * parami;
	float H_vu6g3x1 = mainIn.member6.x * tOne;
	float H_a6xhbf1 = mainIn.member6.y * tOne;
	float H_x5yhxl1 = mainIn.member6.z * tOne;
	float H_nzv3ic1 = H_65zf3k + H_csqbzp1;
	float H_0hg2th1 = H_ftuwyj1 + H_hlu9ip1;
	float H_hdi1ta = H_eppgsd + H_ggjan1;
	float H_km9mym1 = H_8pgueg + H_nzv3ic1;
	float H_23juuc1 = H_0hg2th1 + H_db7vpy;
	float H_o8hblp = H_e9mntx + H_hdi1ta;
	float H_tipemg = H_km9mym1 + H_vu6g3x1;
	float H_hw0egr = H_23juuc1 + H_a6xhbf1;
	float H_my0kid = H_o8hblp + H_x5yhxl1;
	float paramj = C_2d0 * tTwo;
	float H_79r9dr1 = mainIn.member3.x * paramj;
	float H_eon8cq1 = mainIn.member3.y * paramj;
	float H_96qe6f = mainIn.member3.z * paramj;
	float paramk = C_a5d0 * tTwo;
	float H_7gdgtj = mainIn.member4.x * paramk;
	float H_eigw8k1 = mainIn.member4.y * paramk;
	float H_djc9h2 = mainIn.member4.z * paramk;
	float paraml = C_4d0 * tTwo;
	float H_bmnvkf = mainIn.member5.x * paraml;
	float H_ae0ujz = mainIn.member5.y * paraml;
	float H_h6tozw = mainIn.member5.z * paraml;
	float paramm = C_0d0 - tTwo;
	float H_fgikdw = mainIn.member6.x * paramm;
	float H_ux34mt1 = mainIn.member6.y * paramm;
	float H_9u07zi = mainIn.member6.z * paramm;
	float H_g2iz0k1 = H_79r9dr1 + H_tipemg;
	float H_2f5qy = H_eon8cq1 + H_hw0egr;
	float H_nsb5nv1 = H_96qe6f + H_my0kid;
	float H_lcz5zi1 = H_7gdgtj + H_g2iz0k1;
	float H_fpzd8x1 = H_2f5qy + H_eigw8k1;
	float H_j3xngg1 = H_djc9h2 + H_nsb5nv1;
	float H_uks3l2 = H_bmnvkf + H_lcz5zi1;
	float H_wfnlmc = H_ae0ujz + H_fpzd8x1;
	float H_0fiui81 = H_h6tozw + H_j3xngg1;
	float H_wrjn5m1 = H_fgikdw + H_uks3l2;
	float H_r35dmt = H_ux34mt1 + H_wfnlmc;
	float H_ox7soo = H_0fiui81 + H_9u07zi;
	float H_8n6zp91 = C_a0d5 * mainIn.member3.x;
	float H_7csyz91 = C_a0d5 * mainIn.member3.y;
	float H_61ey9a1 = C_a0d5 * mainIn.member3.z;
	float H_v0p6dy1 = C_0d5 * mainIn.member5.x;
	float H_wb373y1 = C_0d5 * mainIn.member5.y;
	float H_tew5xy1 = C_0d5 * mainIn.member5.z;
	float H_k5gk5i = H_8n6zp91 + H_wrjn5m1;
	float H_zz4osu = H_7csyz91 + H_r35dmt;
	float H_p7x7l9 = H_61ey9a1 + H_ox7soo;
	float H_wtgg8d = H_k5gk5i + H_v0p6dy1;
	float H_lonagj = H_wb373y1 + H_zz4osu;
	float H_yyu5ko = H_p7x7l9 + H_tew5xy1;
	vec3 H_4qfm3k = vec3(H_wtgg8d, H_lonagj, H_yyu5ko);
	vec3 vTrailNormal = g_vCameraPositionWs - H_3v83rp;
	vec3 vTrailCrossSectionAxis = cross(H_4qfm3k, vTrailNormal);
	vec3 vTrailCrossSectionAxis1 = normalize(vTrailCrossSectionAxis);
	float H_kw80y2 = H_le24y71 * flT;
	float H_qd6kyp = C_2d0 * mainIn.member4.w;
	float H_gh0wmg = mainIn.member5.w - mainIn.member3.w;
	float H_izxlh31 = H_gh0wmg * flT;
	float H_urhze51 = H_izxlh31 + H_qd6kyp;
	float H_ju0rbk1 = C_2d0 * mainIn.member3.w;
	float H_ralo0q = mainIn.member4.w * C_5d0;
	float H_yj76fd1 = H_ju0rbk1 - H_ralo0q;
	float H_ruevia1 = C_4d0 * mainIn.member5.w;
	float H_6qouzg1 = H_ruevia1 + H_yj76fd1;
	float H_1hwrpc = H_6qouzg1 - mainIn.member6.w;
	float H_cos6ju = H_1hwrpc * H_le24y71;
	float H_a3n5cq = H_cos6ju + H_urhze51;
	float H_37yfuj1 = C_3d0 * mainIn.member4.w;
	float H_upu91t = H_37yfuj1 - mainIn.member3.w;
	float H_szilgj = C_3d0 * mainIn.member5.w;
	float H_rdc7oz = H_upu91t - H_szilgj;
	float H_rzb61x = H_rdc7oz + mainIn.member6.w;
	float H_1mjipv1 = H_kw80y2 * H_rzb61x;
	float H_7dlpjt1 = H_1mjipv1 + H_a3n5cq;
	float H_3o9a6w = C_0d5 * H_7dlpjt1;
	vec2 H_wrmu59 = vec2(H_3o9a6w);
	vec3 vLinearSegment1 = mainIn.member8.xyz / C_vec3p12d92p;
	vec3 H_31sc3o = mainIn.member8.xyz / C_vec3p1d055p;
	vec3 H_bojk8y = C_bw96as + H_31sc3o;
	vec3 vExpSegment1 = pow(H_bojk8y, C_vec3p2d4p);
	bool H_a1xjxr = mainIn.member8.x > C_0d04045;
	float select5 = H_a1xjxr ? vExpSegment1.x : vLinearSegment1.x;
	bool H_xm78gu1 = mainIn.member8.y > C_0d04045;
	float select6 = H_xm78gu1 ? vExpSegment1.y : vLinearSegment1.y;
	bool H_cakbf71 = mainIn.member8.z > C_0d04045;
	float select7 = H_cakbf71 ? vExpSegment1.z : vLinearSegment1.z;
	vec4 H_xxees61 = vec4(select5, select6, select7, mainIn.member8.w);
	vec4 vecTint1 = mix(mainIn.member8, H_xxees61, g_vecExtraData2.x);
	vec4 vecTint2 = mix(vecTint, vecTint1, flT);
	vec2 H_gejkz91 = vec2(H_bzuja31.x, H_mxht6l1.x);
	vec2 H_t712hc = H_gejkz91 * H_wrmu59;
	vec4 H_bwd8u61 = vec4(H_t712hc.x, H_bzuja31.y, H_t712hc.y, H_mxht6l1.y);
	vec4 H_auu1rn1 = vec4(H_bhjmxk, C_0d0, C_1d0, H_3o9a6w);
	float flDistanceFromEyeToParticle = length(vTrailNormal);
	bool H_ab3nes1 = g_vecOrientationFadeControlData.z > C_0d0;
	param = vecTint2;
	param1 = H_3o9a6w;
	if (H_ab3nes1) {
		float H_1fzll = flDistanceFromEyeToParticle * g_vecRadiusControls.y;
		bool H_x7fykr1 = H_3o9a6w > H_1fzll;
		float H_8b8rsy1 = flDistanceFromEyeToParticle * g_vecRadiusControls.z;
		bool H_l8zx3s1 = H_3o9a6w > H_8b8rsy1;
		float H_o5im3j1 = H_3o9a6w - H_1fzll;
		float H_d9g5p91 = g_vecRadiusControls.z - g_vecRadiusControls.y;
		float H_o95ex61 = H_d9g5p91 * flDistanceFromEyeToParticle;
		float H_ft6ieq = H_o5im3j1 / H_o95ex61;
		float H_73ki1y1 = C_1d0 - H_ft6ieq;
		vec4 H_idra8z = vec4(H_73ki1y1);
		vec4 H_zjku8r1 = H_idra8z * vecTint2;
		vec4 select8 = H_l8zx3s1 ? C_vec4p0d0p : H_zjku8r1;
		vec4 select9 = H_x7fykr1 ? select8 : vecTint2;
		float paramn = flDistanceFromEyeToParticle * g_vecRadiusControls.x;
		float paramo = flDistanceFromEyeToParticle * g_vecRadiusControls.w;
		float H_k9bpk21 = clamp(H_3o9a6w, paramn, paramo);
		param = select9;
		param1 = H_k9bpk21;
	}
	vec3 H_pk3dlq1 = vec3(param1);
	vec3 H_xhjc6t = H_pk3dlq1 * vTrailCrossSectionAxis1;
	float _L = C_2d0 * misc3a1.x;
	float _L1 = C_1d0 - _L;
	float H_5es1xm = _L1 * mainIn.member0.x;
	vec3 H_9lsn41 = vec3(H_5es1xm);
	vec3 H_bcfago1 = H_9lsn41 * H_xhjc6t;
	vec3 vecWorldPos = H_3v83rp + H_bcfago1;
	vec4 H_i283401 = vec4(vecWorldPos.x, vecWorldPos.y, vecWorldPos.z, C_1d0);
	vec4 H_bo52ih1 = H_i283401 + g_vWorldToCameraOffsetMultiview[0];
	float dotres = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][0]);
	float dotres1 = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][1]);
	float dotres2 = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][2]);
	float dotres3 = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][3]);
	vec3 H_b734ov1 = g_vCameraDirWs * g_vecDepthControlAndRotationCenterData.xxx;
	vec3 paramp = H_b734ov1 + vecWorldPos;
	vec4 H_p5bmqs1 = vec4(paramp.x, paramp.y, paramp.z, C_1d0);
	vec4 H_vzo6ec = H_p5bmqs1 + g_vWorldToCameraOffsetMultiview[0];
	float dotres4 = dot(H_vzo6ec, g_matWorldToProjectionMultiview[0][2]);
	float dotres5 = dot(H_vzo6ec, g_matWorldToProjectionMultiview[0][3]);
	float H_12kpsg = dotres4 / dotres5;
	float flDesiredZ = H_12kpsg * dotres3;
	float misc2a1 = min(C_0d001, dotres2);
	float misc2a2 = max(flDesiredZ, misc2a1);
	vec3 H_ejiuyb = vecWorldPos - g_vCameraPositionWs;
	float H_yil48l1 = dot(g_vCameraDirWs, H_ejiuyb);
	vec4 H_f4kfbg1 = vec4(vecWorldPos.x, vecWorldPos.y, vecWorldPos.z, H_yil48l1);
	vec3 vCameraToWorld = vecWorldPos - g_vCameraPositionWs;
	vec3 H_tbpgk91 = C_vec3p0d0p - vCameraToWorld;
	vec3 vNormalWs = normalize(H_tbpgk91);
	float H_hinrhc = dot(H_i283401, g_vClipPlane0);
	vec3 H_97llm = g_vRefractControl.zzz * param.xyz;
	vec3 H_htmm3o1 = H_97llm * g_vecBlendControl.zzz;
	vec4 H_aiaonl = param;
	H_aiaonl.xyz = H_htmm3o1.xyz;
	PS_INPUT_gl_m_vTexCoords = H_bwd8u61;
	PS_INPUT_gl_m_vTintColor = H_aiaonl;
	PS_INPUT_gl_vPositionWs_flLinearDepth = H_f4kfbg1;
	PS_INPUT_gl_vNormalWs = vNormalWs;
	PS_INPUT_gl_m_vAnimationBlendValues = H_auu1rn1;
	float H_wwe4bs1 = C_0d0 - dotres1;
	float H_cxj8qc1 = C_2d0 * misc2a2;
	float H_ny4urk = H_cxj8qc1 - dotres3;
	vec4 H_li30bc1 = vec4(dotres, H_wwe4bs1, H_ny4urk, dotres3);
	gl_Position = H_li30bc1;
	gl_ClipDistance[0] = H_hinrhc;
}
