//ATTRIBMAP-50-51-90-53-54-55-56-57-91-xx
#version 330 core
// LunarGOO output
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
struct VS_INPUT {
	vec2 member0;
	vec4 member1;
	vec4 member2;
	vec4 member3;
	vec4 member4;
	vec4 member5;
	vec4 member6;
	vec4 member7;
	vec4 member8;
};
layout(std140, binding = 13 ) uniform PerViewConstantBuffer_t {
	layout(row_major) mat4 g_matWorldToProjection;
	layout(row_major) mat4 g_matProjectionToWorld;
	layout(row_major) mat4 g_matWorldToView;
	layout(row_major) mat4 g_matViewToProjection;
	vec4 g_vInvProjRow3;
	vec4 g_vClipPlane0;
	float g_flToneMapScalarLinear;
	float g_flLightMapScalar;
	float g_flEnvMapScalar;
	float g_flToneMapScalarGamma;
	vec3 g_vCameraPositionWs;
	float g_flViewportMinZ;
	vec3 g_vCameraDirWs;
	float g_flViewportMaxZ;
	vec3 g_vCameraUpDirWs;
	float g_flTime;
	vec3 g_vDepthPsToVsConversion;
	float g_flNearPlane;
	float g_flFarPlane;
	float g_flLightBinnerFarPlane;
	vec2 g_vInvViewportSize;
	vec2 g_vViewportToGBufferRatio;
	vec2 g_vMorphTextureAtlasSize;
	vec4 g_vInvGBufferSize;
	vec2 g_vViewportOffset;
	vec2 g_vViewportSize;
	vec2 g_vRenderTargetSize;
	float g_flFogBlendToBackground;
	float g_flHenyeyGreensteinCoeff;
	vec3 g_vFogColor;
	float g_flNegFogStartOverFogRange;
	float g_flInvFogRange;
	float g_flFogMaxDensity;
	float g_flFogExponent;
	float g_flMod2xIdentity;
	vec2 g_bRoughnessParams;
	float g_bStereoEnabled;
	float g_flStereoCameraIndex;
	vec3 g_vMiddleEyePositionWs;
	float g_flPad2;
	layout(row_major) mat4 g_matWorldToProjectionMultiview[2];
	vec4 g_vCameraPositionWsMultiview[2];
	vec4 g_vFrameBufferCopyInvSizeAndUvScale;
	vec4 g_vCameraAngles;
	vec4 g_vWorldToCameraOffset;
	vec4 g_vWorldToCameraOffsetMultiview[2];
	vec4 g_vPerViewConstantExtraData0;
	vec4 g_vPerViewConstantExtraData1;
	vec4 g_vPerViewConstantExtraData2;
	vec4 g_vPerViewConstantExtraData3;
} ;
layout(std140, binding = 12 ) uniform SpritecardVertexControls_t {
	vec4 g_vecRadiusControls;
	vec4 g_vecExtraData;
	vec4 g_vecSequenceAddressingControls;
	vec4 g_vecDepthControlAndRotationCenterData;
	vec4 g_vecOrientationFadeControlData;
	vec4 g_vecTexelSizeControls;
	vec4 g_vecFinalUVOffsetAndScale;
	vec4 g_vecExtraData2;
} ;
layout(std140, binding = 14 ) uniform SpriteCardPixelControls_t {
	vec4 g_vecPixelControls;
	vec4 g_vecBlendControl;
	vec4 g_vRefractControl;
	vec4 g_vecSeq0Scale;
	vec4 g_vecSeq0Bias;
	vec4 g_vecSeq0AlphaBlendControl;
	vec4 g_vecSeq1Scale;
	vec4 g_vecSeq1Bias;
	vec4 g_vecSeq1AlphaBlendControl;
	vec4 g_vecMotionVectorsControl;
	vec4 g_vColorTransformScale;
	float g_flColorTransformAlphaBias;
	float g_flDesatAmount;
	vec2 _g_vPadding_;
	vec4 g_vecOutlineColor;
	vec4 g_vecOutlineRanges;
	vec4 g_vecHSVShiftShadowDensity;
} ;
layout(std140) uniform DotaGlobalParams_t {
	vec3 g_vGlobalLightDir;
	vec3 g_vGlobalLightColor;
	float g_flGlobalLightSpecularScale;
	vec3 g_vGlobalLightSpecularDir;
	float g_flGlobalLightSpecularExp;
	vec3 g_vGlobalLightSpecularColor;
	float g_flGlobalLightSpecularIndependence;
	vec3 g_vGlobalLightAmbientDir;
	float g_flGlobalLightAmbientScale1;
	vec3 g_vGlobalLightAmbientColor1;
	float g_flGlobalLightAmbientScale2;
	vec3 g_vGlobalLightAmbientColor2;
	float g_flGlobalLightAmbientScale2Hero;
	vec2 g_vGlobalCloud1Offset;
	vec2 g_vGlobalCloud2Offset;
	vec3 g_vFowColor;
	float g_flGlobalCloudScale;
	float g_flFowDarkness;
	float g_flFowGrayFactor;
	float g_flFowColorFactor;
	float g_flFowGrayHilights;
	vec4 g_vFowWorldSize;
	vec4 g_vFowTexOffsets;
	layout(row_major) mat4 g_matShadowWorldToTexture;
	vec4 g_vInvShadowDepthTextureSize;
	vec3 g_vGlobalLightAmbientColor3;
	float g_flGlobalLightAmbientShadowAmount;
} ;
uniform sampler2D g_tFow;
uniform sampler2D g_tFrameBufferCopyTexture;
uniform sampler2D g_tDepthTexture;
uniform sampler2D g_tGBufferAlbedo;
uniform sampler2D g_tGBufferLightingTerms;
uniform sampler2D g_tGBufferDepth;
uniform sampler2D g_tGBufferNormalWs;
layout(std140) uniform PerViewLightingConstantBuffer_t {
	vec4 g_vInvLightTextureDims;
	vec4 g_vLightBinCounts;
	vec2 g_vLowResDeferredLightingTextureDim;
	vec2 g_vLowResDeferredLightingTextureInvDim;
	vec3 g_vToolsAmbientLighting;
	float g_flSSAOEnabled;
	vec3 g_vIrradAtlasInvSize;
	float g_flIrradGlobalLightingFactor;
	vec4 g_vGlobalLightingSHRed;
	vec4 g_vGlobalLightingSHGreen;
	vec4 g_vGlobalLightingSHBlue;
	vec3 g_vRayleighScatteringCoeff;
	float g_flMieScatteringEccentricity;
	vec3 g_vMieScatteringCoeff;
	float g_flMieForwardScatteringRatio;
	vec3 g_vSpecularCubeMapScale;
	float g_flDefaultEnvMapIndex;
	vec4 g_vLightCookieSheetSequenceAndSizes;
	vec3 g_vLpvBoxMinCascade0;
	float g_flLpvBrightnessScale;
	vec3 g_vLpvInvBoxDimCascade0;
	vec2 g_vLpvInvCoeffTextureDim;
} ;
layout(std140) uniform PerLayerConstantBuffer_t {
	vec4 g_vWireframeColor;
} ;
uniform sampler2D g_tParticleSheetTexture;
layout(std140) uniform SpritecardSheetData_t {
	vec4 g_vSheetDataIndex;
} ;
layout(std140) uniform SpritecardNormalSheetData_t {
	vec4 g_vNormalSheetDataIndex;
} ;
layout(std140) uniform SpritecardMotionVectorsSheetData_t {
	vec4 g_vMotionVectorsSheetDataIndex;
} ;
uniform sampler2D g_tBaseTexture;
uniform sampler2D g_tBaseTextureNoSRGB;
uniform sampler2D g_tClouds;
uniform sampler2DShadow g_tShadowDepthTexture;
layout(location=0) in vec2 VS_INPUT_gl_m_vCornerID;
layout(location=1) in vec4 VS_INPUT_gl_m_vSequenceAndTimeData;
layout(location=2) in vec4 VS_INPUT_gl_m_vTint;
layout(location=3) in vec4 VS_INPUT_gl_m_vPosAndRadius0;
layout(location=4) in vec4 VS_INPUT_gl_m_vPosAndRadius1;
layout(location=5) in vec4 VS_INPUT_gl_m_vPosAndRadius2;
layout(location=6) in vec4 VS_INPUT_gl_m_vPosAndRadius3;
layout(location=7) in vec4 VS_INPUT_gl_m_vCropDomain;
layout(location=8) in vec4 VS_INPUT_gl_m_vTint1;
out gl_PerVertex {
	vec4 gl_Position;
	float gl_ClipDistance[1];
} ;
layout(location=0) out vec4 PS_INPUT_gl_m_vTexCoords;
layout(location=1) out vec4 PS_INPUT_gl_m_vTintColor;
layout(location=2) out vec4 PS_INPUT_gl_vPositionWs_flLinearDepth;
layout(location=3) out vec3 PS_INPUT_gl_vNormalWs;
layout(location=4) out vec4 PS_INPUT_gl_m_vAnimationBlendValues;
const float C_0d0 = 0.0;
const vec2 C_vec2p2d0p = vec2(2.0);
const vec2 C_vec2pa1d0p = vec2(-1.0);
const float C_0d5 = 0.5;
const float C_1d0 = 1.0;
const float C_a0d5 = -0.5;
const vec3 C_vec3p12d92p = vec3(12.92);
const vec3 C_vec3p1d055p = vec3(1.055);
const vec3 C_bw96as = vec3(0.0521327);
const vec3 C_vec3p2d4p = vec3(2.4);
const float C_0d04045 = 0.04045;
const float C_3d0 = 3.0;
const float C_a3d0 = -3.0;
const float C_2d0 = 2.0;
const float C_a5d0 = -5.0;
const float C_4d0 = 4.0;
const float C_5d0 = 5.0;
const vec4 C_8k04jx = vec4(1.0, 0.0, 1.0, 0.0);
const vec4 C_vec4p0d0p = vec4(0.0);
const float C_0d001 = 0.001;
const vec3 C_vec3p0d0p = vec3(0.0);
void main()
{
	vec4 param;
	float param1;
	VS_INPUT param2;
	VS_INPUT mainIn;
	mainIn.member0 = VS_INPUT_gl_m_vCornerID;
	mainIn.member1 = VS_INPUT_gl_m_vSequenceAndTimeData;
	mainIn.member2 = VS_INPUT_gl_m_vTint;
	mainIn.member3 = VS_INPUT_gl_m_vPosAndRadius0;
	mainIn.member4 = VS_INPUT_gl_m_vPosAndRadius1;
	mainIn.member5 = VS_INPUT_gl_m_vPosAndRadius2;
	mainIn.member6 = VS_INPUT_gl_m_vPosAndRadius3;
	mainIn.member7 = VS_INPUT_gl_m_vCropDomain;
	mainIn.member8 = VS_INPUT_gl_m_vTint1;
	gl_ClipDistance[0] = C_0d0;
	vec2 H_x3n5dv1 = mainIn.member7.zw * C_vec2p2d0p;
	vec2 vFlip = H_x3n5dv1 + C_vec2pa1d0p;
	vec2 vCornerCoords = mainIn.member0 * vFlip;
	float H_v1fmof = vCornerCoords.x * C_0d5;
	float H_yuxxyt = C_1d0 - mainIn.member7.x;
	float H_3q8ngg = H_v1fmof * H_yuxxyt;
	float H_kl1lkh1 = C_0d5 + H_3q8ngg;
	float H_7ttbnz = vCornerCoords.y * C_a0d5;
	float H_xjjx8u = C_1d0 - mainIn.member7.y;
	float H_3jiog11 = H_7ttbnz * H_xjjx8u;
	float H_0zvieu = C_0d5 + H_3jiog11;
	vec4 H_qex72y = vec4(H_kl1lkh1, H_0zvieu, H_kl1lkh1, H_0zvieu);
	float H_jzvcmi = C_0d5 * mainIn.member0.y;
	float H_p1o5jw = C_0d5 + H_jzvcmi;
	float flDistance = mix(mainIn.member1.x, mainIn.member1.y, H_p1o5jw);
	vec4 H_p0dmbm = H_qex72y * g_vecFinalUVOffsetAndScale.zwzw;
	vec4 H_ilubi9 = H_p0dmbm + g_vecFinalUVOffsetAndScale.xyxy;
	float H_48kbar1 = flDistance + g_vecTexelSizeControls.z;
	float H_5beijh1 = H_48kbar1 * g_vecTexelSizeControls.w;
	float H_qmduo9 = H_5beijh1 * g_vecFinalUVOffsetAndScale.w;
	float H_k1gvhu = H_qmduo9 + g_vecFinalUVOffsetAndScale.y;
	vec2 H_fid00w = vec2(H_k1gvhu);
	vec2 H_j35pl6 = mix(H_ilubi9.yw, H_fid00w, g_vecTexelSizeControls.x);
	vec3 vLinearSegment = mainIn.member2.xyz / C_vec3p12d92p;
	vec3 H_5wer1f1 = mainIn.member2.xyz / C_vec3p1d055p;
	vec3 H_ctvgtv1 = H_5wer1f1 + C_bw96as;
	vec3 vExpSegment = pow(H_ctvgtv1, C_vec3p2d4p);
	bool H_0rpnph = mainIn.member2.x > C_0d04045;
	float select = H_0rpnph ? vExpSegment.x : vLinearSegment.x;
	bool H_rh3dd11 = mainIn.member2.y > C_0d04045;
	float select1 = H_rh3dd11 ? vExpSegment.y : vLinearSegment.y;
	bool H_y1yyma1 = mainIn.member2.z > C_0d04045;
	float select2 = H_y1yyma1 ? vExpSegment.z : vLinearSegment.z;
	vec4 H_k5jx7i1 = vec4(select, select1, select2, mainIn.member2.w);
	vec4 vecTint = mix(mainIn.member2, H_k5jx7i1, g_vecExtraData2.x);
	float H_78z17d1 = H_p1o5jw * H_p1o5jw;
	float tSqr = C_0d5 * H_78z17d1;
	float tSqrSqr = H_p1o5jw * tSqr;
	float H_5imfao1 = C_0d5 * H_p1o5jw;
	float param3 = C_0d0 - tSqrSqr;
	float H_0c7q53 = mainIn.member3.x * param3;
	float H_xiiu2b1 = mainIn.member3.y * param3;
	float H_688zzp = mainIn.member3.z * param3;
	float param4 = tSqrSqr * C_3d0;
	float H_uit3g3 = mainIn.member4.x * param4;
	float H_bnvn311 = mainIn.member4.y * param4;
	float H_w9z96r = mainIn.member4.z * param4;
	float param5 = tSqrSqr * C_a3d0;
	float H_g6yb74 = mainIn.member5.x * param5;
	float H_pxc7df1 = mainIn.member5.y * param5;
	float H_2j8q4l1 = mainIn.member5.z * param5;
	float H_9tzyi41 = mainIn.member6.x * tSqrSqr;
	float H_a400ur1 = mainIn.member6.y * tSqrSqr;
	float H_fakfa2 = mainIn.member6.z * tSqrSqr;
	float H_g8d3tp1 = H_0c7q53 + H_uit3g3;
	float H_ps58fb1 = H_bnvn311 + H_xiiu2b1;
	float H_996s211 = H_688zzp + H_w9z96r;
	float H_umq7jv = H_g6yb74 + H_g8d3tp1;
	float H_uy3bt8 = H_ps58fb1 + H_pxc7df1;
	float H_7be0w71 = H_2j8q4l1 + H_996s211;
	float H_scajbg1 = H_9tzyi41 + H_umq7jv;
	float H_qld4nj = H_a400ur1 + H_uy3bt8;
	float H_itkcm8 = H_7be0w71 + H_fakfa2;
	float param6 = tSqr * C_2d0;
	float H_vs7oj4 = mainIn.member3.x * param6;
	float H_ulbtwb1 = mainIn.member3.y * param6;
	float H_1p8xdr = mainIn.member3.z * param6;
	float param7 = tSqr * C_a5d0;
	float H_vt7463 = mainIn.member4.x * param7;
	float H_achnd11 = mainIn.member4.y * param7;
	float H_tcs80s = mainIn.member4.z * param7;
	float param8 = tSqr * C_4d0;
	float H_j35dd3 = mainIn.member5.x * param8;
	float H_2xicrb1 = mainIn.member5.y * param8;
	float H_5gfrak1 = mainIn.member5.z * param8;
	float param9 = C_0d0 - tSqr;
	float H_7z03l81 = mainIn.member6.x * param9;
	float H_mou5of = mainIn.member6.y * param9;
	float H_twcmex = mainIn.member6.z * param9;
	float H_i56z6o1 = H_scajbg1 + H_vs7oj4;
	float H_61mc8g = H_qld4nj + H_ulbtwb1;
	float H_t2w93o1 = H_1p8xdr + H_itkcm8;
	float H_4y9vji = H_i56z6o1 + H_vt7463;
	float H_mud3o4 = H_61mc8g + H_achnd11;
	float H_k8tady1 = H_t2w93o1 + H_tcs80s;
	float H_m555jw = H_4y9vji + H_j35dd3;
	float H_douvv01 = H_2xicrb1 + H_mud3o4;
	float H_roo6lt1 = H_5gfrak1 + H_k8tady1;
	float H_kjgsm9 = H_7z03l81 + H_m555jw;
	float H_o51r9a1 = H_douvv01 + H_mou5of;
	float H_pocnud1 = H_roo6lt1 + H_twcmex;
	float parama = C_0d0 - H_5imfao1;
	float H_eejcfp1 = mainIn.member3.x * parama;
	float H_nf8cun1 = mainIn.member3.y * parama;
	float H_kj3j4c = mainIn.member3.z * parama;
	float H_lvmhoq1 = H_5imfao1 * mainIn.member5.x;
	float H_m61ieq1 = H_5imfao1 * mainIn.member5.y;
	float H_nhfi4q1 = H_5imfao1 * mainIn.member5.z;
	float H_hzqi1h1 = H_eejcfp1 + H_kjgsm9;
	float H_72ah0k = H_nf8cun1 + H_o51r9a1;
	float H_z7rgnk1 = H_kj3j4c + H_pocnud1;
	float H_o9qzek1 = H_hzqi1h1 + H_lvmhoq1;
	float H_hd67x2 = H_72ah0k + H_m61ieq1;
	float H_f8dvjo = H_nhfi4q1 + H_z7rgnk1;
	float H_l7u3z61 = H_o9qzek1 + mainIn.member4.x;
	float H_fuprse = H_hd67x2 + mainIn.member4.y;
	float H_4l2wfw1 = H_f8dvjo + mainIn.member4.z;
	vec3 H_sczsm6 = vec3(H_l7u3z61, H_fuprse, H_4l2wfw1);
	float H_7xvjhm1 = C_3d0 * H_p1o5jw;
	float H_6cj7951 = H_7xvjhm1 * H_p1o5jw;
	float tOne = C_0d5 * H_6cj7951;
	float H_qajsyg1 = C_2d0 * H_p1o5jw;
	float tTwo = C_0d5 * H_qajsyg1;
	float paramb = C_0d0 - tOne;
	float H_fpxc5p1 = mainIn.member3.x * paramb;
	float H_m4ub4o1 = mainIn.member3.y * paramb;
	float H_hmwhyc = mainIn.member3.z * paramb;
	float paramc = C_3d0 * tOne;
	float H_fwjjlh = mainIn.member4.x * paramc;
	float H_62atgm1 = mainIn.member4.y * paramc;
	float H_5366p4 = mainIn.member4.z * paramc;
	float paramd = C_a3d0 * tOne;
	float H_36hssh = mainIn.member5.x * paramd;
	float H_2ytqr11 = mainIn.member5.y * paramd;
	float H_9qml7z = mainIn.member5.z * paramd;
	float H_vu6g3x1 = mainIn.member6.x * tOne;
	float H_a6xhbf1 = mainIn.member6.y * tOne;
	float H_x5yhxl1 = mainIn.member6.z * tOne;
	float H_ivwvtc = H_fpxc5p1 + H_fwjjlh;
	float H_got1fu1 = H_62atgm1 + H_m4ub4o1;
	float H_6cmwa21 = H_5366p4 + H_hmwhyc;
	float H_c52gyc1 = H_36hssh + H_ivwvtc;
	float H_76o79q = H_2ytqr11 + H_got1fu1;
	float H_t1ex991 = H_6cmwa21 + H_9qml7z;
	float H_w1bu2h = H_c52gyc1 + H_vu6g3x1;
	float H_tohe9r1 = H_76o79q + H_a6xhbf1;
	float H_4pswfc = H_t1ex991 + H_x5yhxl1;
	float parame = C_2d0 * tTwo;
	float H_a6yajq1 = mainIn.member3.x * parame;
	float H_j7nayo1 = mainIn.member3.y * parame;
	float H_gbih8d = mainIn.member3.z * parame;
	float paramf = C_a5d0 * tTwo;
	float H_kfjl7g = mainIn.member4.x * paramf;
	float H_1jarun1 = mainIn.member4.y * paramf;
	float H_26z4j5 = mainIn.member4.z * paramf;
	float paramg = C_4d0 * tTwo;
	float H_2v2s2i = mainIn.member5.x * paramg;
	float H_398rh11 = mainIn.member5.y * paramg;
	float H_cntmdy = mainIn.member5.z * paramg;
	float paramh = C_0d0 - tTwo;
	float H_kzhmzu = mainIn.member6.x * paramh;
	float H_xua5ss1 = mainIn.member6.y * paramh;
	float H_6xt5tj = mainIn.member6.z * paramh;
	float H_k08eut1 = H_a6yajq1 + H_w1bu2h;
	float H_br0zed1 = H_j7nayo1 + H_tohe9r1;
	float H_1gmqpk = H_4pswfc + H_gbih8d;
	float H_j8qh9l1 = H_k08eut1 + H_kfjl7g;
	float H_manrv21 = H_1jarun1 + H_br0zed1;
	float H_o5fk7r = H_1gmqpk + H_26z4j5;
	float H_p1o7jx1 = H_2v2s2i + H_j8qh9l1;
	float H_vgpanc1 = H_398rh11 + H_manrv21;
	float H_n0ij0s = H_cntmdy + H_o5fk7r;
	float H_rupxyk1 = H_kzhmzu + H_p1o7jx1;
	float H_y1mz5o = H_vgpanc1 + H_xua5ss1;
	float H_fxfw43 = H_6xt5tj + H_n0ij0s;
	float H_8n6zp91 = C_a0d5 * mainIn.member3.x;
	float H_7csyz91 = C_a0d5 * mainIn.member3.y;
	float H_61ey9a1 = C_a0d5 * mainIn.member3.z;
	float H_v0p6dy1 = C_0d5 * mainIn.member5.x;
	float H_wb373y1 = C_0d5 * mainIn.member5.y;
	float H_tew5xy1 = C_0d5 * mainIn.member5.z;
	float H_i4brif = H_8n6zp91 + H_rupxyk1;
	float H_lt6uga = H_7csyz91 + H_y1mz5o;
	float H_uj4xa4 = H_61ey9a1 + H_fxfw43;
	float H_iwhle01 = H_i4brif + H_v0p6dy1;
	float H_997438 = H_lt6uga + H_wb373y1;
	float H_l78t241 = H_tew5xy1 + H_uj4xa4;
	vec3 H_uiya3i = vec3(H_iwhle01, H_997438, H_l78t241);
	vec3 vTrailNormal = g_vCameraPositionWs - H_sczsm6;
	vec3 vTrailCrossSectionAxis = cross(H_uiya3i, vTrailNormal);
	vec3 vTrailCrossSectionAxis1 = normalize(vTrailCrossSectionAxis);
	float H_f34a89 = H_78z17d1 * H_p1o5jw;
	float H_qd6kyp = C_2d0 * mainIn.member4.w;
	float H_gh0wmg = mainIn.member5.w - mainIn.member3.w;
	float H_9vy0ya = H_gh0wmg * H_p1o5jw;
	float H_hplzk1 = H_9vy0ya + H_qd6kyp;
	float H_ju0rbk1 = C_2d0 * mainIn.member3.w;
	float H_ralo0q = mainIn.member4.w * C_5d0;
	float H_yj76fd1 = H_ju0rbk1 - H_ralo0q;
	float H_ruevia1 = C_4d0 * mainIn.member5.w;
	float H_6qouzg1 = H_ruevia1 + H_yj76fd1;
	float H_1hwrpc = H_6qouzg1 - mainIn.member6.w;
	float H_0zj5je1 = H_1hwrpc * H_78z17d1;
	float H_z4ltaq = H_0zj5je1 + H_hplzk1;
	float H_37yfuj1 = C_3d0 * mainIn.member4.w;
	float H_upu91t = H_37yfuj1 - mainIn.member3.w;
	float H_szilgj = C_3d0 * mainIn.member5.w;
	float H_rdc7oz = H_upu91t - H_szilgj;
	float H_rzb61x = H_rdc7oz + mainIn.member6.w;
	float H_bm4jxw1 = H_f34a89 * H_rzb61x;
	float H_piqev2 = H_bm4jxw1 + H_z4ltaq;
	float H_k3if8a = C_0d5 * H_piqev2;
	vec2 H_vtgiak = vec2(H_k3if8a);
	vec3 vLinearSegment1 = mainIn.member8.xyz / C_vec3p12d92p;
	vec3 H_31sc3o = mainIn.member8.xyz / C_vec3p1d055p;
	vec3 H_bojk8y = C_bw96as + H_31sc3o;
	vec3 vExpSegment1 = pow(H_bojk8y, C_vec3p2d4p);
	bool H_a1xjxr = mainIn.member8.x > C_0d04045;
	float select3 = H_a1xjxr ? vExpSegment1.x : vLinearSegment1.x;
	bool H_xm78gu1 = mainIn.member8.y > C_0d04045;
	float select4 = H_xm78gu1 ? vExpSegment1.y : vLinearSegment1.y;
	bool H_cakbf71 = mainIn.member8.z > C_0d04045;
	float select5 = H_cakbf71 ? vExpSegment1.z : vLinearSegment1.z;
	vec4 H_vrq1a1 = vec4(select3, select4, select5, mainIn.member8.w);
	vec4 vecTint1 = mix(mainIn.member8, H_vrq1a1, g_vecExtraData2.x);
	vec4 vecTint2 = mix(vecTint, vecTint1, H_p1o5jw);
	vec2 H_t9yim11 = H_ilubi9.xz * H_vtgiak;
	vec4 H_k277rj = vec4(H_t9yim11.x, H_j35pl6.x, H_t9yim11.y, H_j35pl6.y);
	vec4 H_gpimr81 = C_8k04jx;
	H_gpimr81.w = H_k3if8a;
	float flDistanceFromEyeToParticle = length(vTrailNormal);
	bool H_ab3nes1 = g_vecOrientationFadeControlData.z > C_0d0;
	param = vecTint2;
	param1 = H_k3if8a;
	if (H_ab3nes1) {
		float H_1fzll = flDistanceFromEyeToParticle * g_vecRadiusControls.y;
		bool H_wapguv = H_k3if8a > H_1fzll;
		float H_8b8rsy1 = flDistanceFromEyeToParticle * g_vecRadiusControls.z;
		bool H_0bio7z = H_k3if8a > H_8b8rsy1;
		float H_t7tr9i = H_k3if8a - H_1fzll;
		float H_d9g5p91 = g_vecRadiusControls.z - g_vecRadiusControls.y;
		float H_o95ex61 = H_d9g5p91 * flDistanceFromEyeToParticle;
		float H_4ofh5o = H_t7tr9i / H_o95ex61;
		float H_t2thgd = C_1d0 - H_4ofh5o;
		vec4 H_wux6y81 = vec4(H_t2thgd);
		vec4 H_7t3b5j = H_wux6y81 * vecTint2;
		vec4 select6 = H_0bio7z ? C_vec4p0d0p : H_7t3b5j;
		vec4 select7 = H_wapguv ? select6 : vecTint2;
		float parami = flDistanceFromEyeToParticle * g_vecRadiusControls.x;
		float paramj = flDistanceFromEyeToParticle * g_vecRadiusControls.w;
		float H_dlu314 = clamp(H_k3if8a, parami, paramj);
		param = select7;
		param1 = H_dlu314;
	}
	vec3 H_pk3dlq1 = vec3(param1);
	vec3 H_xhjc6t = H_pk3dlq1 * vTrailCrossSectionAxis1;
	vec3 H_tsc5r = H_xhjc6t * mainIn.member0.xxx;
	vec3 vecWorldPos = H_sczsm6 + H_tsc5r;
	vec4 H_i283401 = vec4(vecWorldPos.x, vecWorldPos.y, vecWorldPos.z, C_1d0);
	vec4 H_bo52ih1 = H_i283401 + g_vWorldToCameraOffsetMultiview[0];
	float dotres = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][0]);
	float dotres1 = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][1]);
	float dotres2 = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][2]);
	float dotres3 = dot(H_bo52ih1, g_matWorldToProjectionMultiview[0][3]);
	vec3 H_b734ov1 = g_vCameraDirWs * g_vecDepthControlAndRotationCenterData.xxx;
	vec3 paramk = H_b734ov1 + vecWorldPos;
	vec4 H_kqbf32 = vec4(paramk.x, paramk.y, paramk.z, C_1d0);
	vec4 H_fv7d37 = H_kqbf32 + g_vWorldToCameraOffsetMultiview[0];
	float dotres4 = dot(H_fv7d37, g_matWorldToProjectionMultiview[0][2]);
	float dotres5 = dot(H_fv7d37, g_matWorldToProjectionMultiview[0][3]);
	float H_12kpsg = dotres4 / dotres5;
	float flDesiredZ = H_12kpsg * dotres3;
	float misc2a = min(C_0d001, dotres2);
	float misc2a1 = max(flDesiredZ, misc2a);
	vec3 H_ejiuyb = vecWorldPos - g_vCameraPositionWs;
	float H_yil48l1 = dot(g_vCameraDirWs, H_ejiuyb);
	vec4 H_f4kfbg1 = vec4(vecWorldPos.x, vecWorldPos.y, vecWorldPos.z, H_yil48l1);
	vec3 vCameraToWorld = vecWorldPos - g_vCameraPositionWs;
	vec3 H_tbpgk91 = C_vec3p0d0p - vCameraToWorld;
	vec3 vNormalWs = normalize(H_tbpgk91);
	float H_hinrhc = dot(H_i283401, g_vClipPlane0);
	vec3 H_97llm = g_vRefractControl.zzz * param.xyz;
	vec3 H_htmm3o1 = H_97llm * g_vecBlendControl.zzz;
	vec4 H_aiaonl = param;
	H_aiaonl.xyz = H_htmm3o1.xyz;
	PS_INPUT_gl_m_vTexCoords = H_k277rj;
	PS_INPUT_gl_m_vTintColor = H_aiaonl;
	PS_INPUT_gl_vPositionWs_flLinearDepth = H_f4kfbg1;
	PS_INPUT_gl_vNormalWs = vNormalWs;
	PS_INPUT_gl_m_vAnimationBlendValues = H_gpimr81;
	float H_wwe4bs1 = C_0d0 - dotres1;
	float H_90d7kd1 = C_2d0 * misc2a1;
	float H_hs5rdw = H_90d7kd1 - dotres3;
	vec4 H_3u6ent1 = vec4(dotres, H_wwe4bs1, H_hs5rdw, dotres3);
	gl_Position = H_3u6ent1;
	gl_ClipDistance[0] = H_hinrhc;
}
