#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable
uniform 	vec4 _Time;
uniform 	vec4 unity_FogColor;
uniform 	vec4 _AmbientLightColor;
uniform 	vec4 _DirectionalLightColor;
uniform 	vec3 _DirectionalLightForward;
uniform 	vec4 _PointLightColor;
uniform 	vec4 _PointLightDistances;
uniform 	vec4 _PointLightIntensities;
uniform 	float _PointLightAmbientFalloff;
uniform 	vec3 _VertexAnimSpeed;
uniform 	vec3 _VertexAnimRepeat;
uniform 	vec3 _VertexAnimScale;
uniform 	vec4 _DepthColor;
uniform 	vec2 _DepthBounds;
in  vec4 vs_COLOR0;
in  vec3 vs_TEXCOORD0;
in  float vs_TEXCOORD5;
in  vec4 vs_TEXCOORD1;
in  vec3 vs_TEXCOORD2;
in  vec3 vs_TEXCOORD3;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat0;
vec4 u_xlat1;
bvec4 u_xlatb1;
vec4 u_xlat2;
vec3 u_xlat3;
float u_xlat6;
float u_xlat9;
void main()
{
    u_xlat0.x = vs_TEXCOORD1.x * _VertexAnimRepeat.x;
    u_xlat0.x = _Time.y * _VertexAnimSpeed.x + u_xlat0.x;
    u_xlat0.x = _VertexAnimRepeat.y * vs_TEXCOORD1.z + u_xlat0.x;
    u_xlat0.x = u_xlat0.x * 5.0;
    u_xlat0.x = sin((-u_xlat0.x));
    u_xlat0.x = u_xlat0.x + 1.0;
    u_xlat3.x = _VertexAnimScale.x * 0.699999988;
    u_xlat0.x = u_xlat3.x * u_xlat0.x + vs_TEXCOORD1.y;
    u_xlat0.x = u_xlat0.x + (-_DepthBounds.y);
    u_xlat3.x = (-_DepthBounds.y) + _DepthBounds.x;
    u_xlat0.x = u_xlat0.x / u_xlat3.x;
    u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0);
    u_xlat0.x = (-u_xlat0.x) + 1.0;
    u_xlat3.x = dot(vs_TEXCOORD2.xyz, vs_TEXCOORD2.xyz);
    u_xlat6 = dot(vs_TEXCOORD3.xyz, vs_TEXCOORD3.xyz);
    u_xlat3.x = min(u_xlat6, u_xlat3.x);
    u_xlat3.x = (-u_xlat3.x) + 1.0;
    u_xlat3.x = max(u_xlat3.x, 0.00100000005);
    u_xlat3.x = float(1.0) / u_xlat3.x;
    u_xlat3.x = u_xlat3.x + -1.0;
    u_xlat3.x = u_xlat3.x * 0.0399999991;
    u_xlat3.x = sqrt(u_xlat3.x);
    u_xlatb1 = greaterThanEqual(_PointLightDistances, u_xlat3.xxxx);
    u_xlat1 = mix(vec4(0.0, 0.0, 0.0, 0.0), vec4(1.0, 1.0, 1.0, 1.0), vec4(u_xlatb1));
    u_xlat2.yzw = u_xlat1.xyz;
    u_xlat2.x = 0.0;
    u_xlat1 = u_xlat1 + (-u_xlat2);
    u_xlat3.x = dot(u_xlat1, _PointLightIntensities);
    u_xlat6 = dot(vs_TEXCOORD0.xyz, vs_TEXCOORD0.xyz);
    u_xlat6 = inversesqrt(u_xlat6);
    u_xlat1.xyz = vec3(u_xlat6) * vs_TEXCOORD0.xyz;
    u_xlat6 = dot(u_xlat1.xyz, _DirectionalLightForward.xyz);
    u_xlat9 = (-u_xlat6) + 1.0;
    u_xlat9 = _PointLightAmbientFalloff * u_xlat9 + u_xlat6;
    u_xlat3.x = u_xlat9 * u_xlat3.x;
    u_xlat1.xyz = u_xlat3.xxx * _PointLightColor.xyz;
    u_xlat3.xyz = vec3(u_xlat6) * _DirectionalLightColor.xyz + u_xlat1.xyz;
    u_xlat1.xyz = vs_COLOR0.xyz * _AmbientLightColor.xyz;
    u_xlat1.xyz = vs_COLOR0.xyz * u_xlat3.xyz + u_xlat1.xyz;
    u_xlat1.w = vs_COLOR0.w;
    u_xlat2 = (-u_xlat1) + _DepthColor;
    u_xlat0 = u_xlat0.xxxx * u_xlat2;
    u_xlat0 = _DepthColor.wwww * u_xlat0 + u_xlat1;
    u_xlat0.xyz = u_xlat0.xyz + (-unity_FogColor.xyz);
    SV_Target0.w = u_xlat0.w;
    u_xlat9 = vs_TEXCOORD5;
    u_xlat9 = clamp(u_xlat9, 0.0, 1.0);
    SV_Target0.xyz = vec3(u_xlat9) * u_xlat0.xyz + unity_FogColor.xyz;
    return;
}